import { useAccess } from '@/hooks/useAccess'
import { ONLY_PC_PAGE } from '@/router/config'

/**
 * 工作台菜单数据
 * 定义菜单分组和菜单项的数据结构
 */

/** 菜单项类型 */
export interface MenuItem {
  key: string // 菜单唯一标识
  name: string // 菜单名称
  icon: string // 菜单图标（支持 @wot-ui/ui 图标名或图片路径）
  url?: string // 跳转路径
  iconColor?: string // 图标颜色（可选）
  enabled?: boolean // 是否启用（可选，默认 true）
  permission?: string // 权限标识（可选）
}

/** 菜单分组类型 */
export interface MenuGroup {
  key: string // 分组唯一标识
  name: string // 分组名称
  menus: MenuItem[] // 分组下的菜单列表
}

/** 菜单分组原始数据 */
const menuGroupsData: MenuGroup[] = [
  {
    key: 'system',
    name: 'SYSTEM 系统管理',
    menus: [
      {
        key: 'user',
        name: '用户管理',
        icon: 'user',
        url: '/pages-system/user/index',
        iconColor: '#1890ff',
        permission: 'system:user:list',
      },
      {
        key: 'role',
        name: '角色管理',
        icon: 'safe',
        url: '/pages-system/role/index',
        iconColor: '#2f54eb',
        permission: 'system:role:query',
      },
      {
        key: 'menu',
        name: '菜单管理',
        icon: 'menu-fold',
        url: '/pages-system/menu/index',
        iconColor: '#597ef7',
        permission: 'system:menu:query',
      },
      {
        key: 'dept',
        name: '部门管理',
        icon: 'organization',
        url: '/pages-system/dept/index',
        iconColor: '#13c2c2',
        permission: 'system:dept:query',
      },
      {
        key: 'post',
        name: '岗位管理',
        icon: 'idcard',
        url: '/pages-system/post/index',
        iconColor: '#36cfc9',
        permission: 'system:post:query',
      },
      {
        key: 'operateLog',
        name: '操作日志',
        icon: 'history',
        url: '/pages-system/operate-log/index',
        iconColor: '#722ed1',
        permission: 'system:operate-log:query',
      },
      {
        key: 'loginLog',
        name: '登录日志',
        icon: 'import',
        url: '/pages-system/login-log/index',
        iconColor: '#9254de',
        permission: 'system:login-log:query',
      },
      {
        key: 'notice',
        name: '通知公告',
        icon: 'notification',
        url: '/pages-system/notice/index',
        iconColor: '#fa8c16',
        permission: 'system:notice:query',
      },
      {
        key: 'sms',
        name: '短信管理',
        icon: 'message',
        url: '/pages-system/sms/index',
        iconColor: '#faad14',
        permission: 'system:sms-channel:query',
      },
      {
        key: 'mail',
        name: '邮件管理',
        icon: 'email',
        url: '/pages-system/mail/index',
        iconColor: '#ffc53d',
        permission: 'system:mail-account:query',
      },
      {
        key: 'notify',
        name: '站内信管理',
        icon: 'message',
        url: '/pages-system/notify/index',
        iconColor: '#ff7a45',
        permission: 'system:notify-template:query',
      },
      {
        key: 'tenant',
        name: '租户管理',
        icon: 'store',
        url: '/pages-system/tenant/index',
        iconColor: '#eb2f96',
        permission: 'system:tenant:query',
      },
      {
        key: 'social',
        name: '三方用户',
        icon: 'share-alt',
        url: '/pages-system/social/index',
        iconColor: '#f759ab',
        permission: 'system:social-client:query',
      },
      {
        key: 'oauth2',
        name: 'OAuth2.0',
        icon: 'lock',
        url: '/pages-system/oauth2/index',
        iconColor: '#ff85c0',
        permission: 'system:oauth2-client:query',
      },
      {
        key: 'dict',
        name: '字典管理',
        icon: 'book',
        url: '/pages-system/dict/index',
        iconColor: '#c41d7f',
        permission: 'system:dict:query',
      },
      {
        key: 'area',
        name: '地区管理',
        icon: 'location',
        url: '/pages-system/area/index',
        iconColor: '#f5222d',
      },
    ],
  },
  {
    key: 'im',
    name: 'IM 即时通讯',
    menus: [
      {
        key: 'imHome',
        name: '聊天',
        icon: 'message',
        url: '/pages-im/home/index/index',
        iconColor: '#1677ff',
      },
      {
        key: 'imStatistics',
        name: '数据统计',
        icon: 'dashboard',
        url: '/pages-im/manager/index/index',
        iconColor: '#722ed1',
      },
      {
        key: 'imFriend',
        name: '好友列表',
        icon: 'user',
        url: '/pages-im/manager/friend/index',
        iconColor: '#1890ff',
      },
      {
        key: 'imFriendRequest',
        name: '好友申请',
        icon: 'user-add',
        url: '/pages-im/manager/friend/request/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'imPrivateMessage',
        name: '好友消息',
        icon: 'message',
        url: '/pages-im/manager/message/private/index',
        iconColor: '#722ed1',
      },
      {
        key: 'imGroup',
        name: '群聊列表',
        icon: 'user-group',
        url: '/pages-im/manager/group/index',
        iconColor: '#52c41a',
      },
      {
        key: 'imGroupRequest',
        name: '群聊申请',
        icon: 'user-add',
        url: '/pages-im/manager/group/request/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'imGroupMessage',
        name: '群聊消息',
        icon: 'message',
        url: '/pages-im/manager/message/group/index',
        iconColor: '#eb2f96',
      },
      {
        key: 'imRtc',
        name: '通话记录',
        icon: 'phone',
        url: '/pages-im/manager/rtc/index',
        iconColor: '#08979c',
      },
      {
        key: 'imSensitiveWord',
        name: '敏感词管理',
        icon: 'message-banned',
        url: '/pages-im/manager/sensitive-word/index',
        iconColor: '#f5222d',
      },
      {
        key: 'imFacePack',
        name: '系统表情',
        icon: 'face-smile-fill',
        url: '/pages-im/manager/face/pack/index',
        iconColor: '#9254de',
      },
      {
        key: 'imFaceUserItem',
        name: '用户表情',
        icon: 'face-meh-fill',
        url: '/pages-im/manager/face/user-item/index',
        iconColor: '#36cfc9',
      },
      {
        key: 'imChannel',
        name: '频道列表',
        icon: 'send',
        url: '/pages-im/manager/channel/index',
        iconColor: '#2f54eb',
      },
      {
        key: 'imChannelMaterial',
        name: '频道素材',
        icon: 'image',
        url: '/pages-im/manager/channel/material/index',
        iconColor: '#fa541c',
      },
      {
        key: 'imChannelMessage',
        name: '频道消息',
        icon: 'email',
        url: '/pages-im/manager/channel/message/index',
        iconColor: '#faad14',
      },
    ],
  },
  {
    key: 'infra',
    name: 'INFRA 基础设施',
    menus: [
      {
        key: 'accessLog',
        name: '访问日志',
        icon: 'list',
        url: '/pages-infra/api-access-log/index',
        iconColor: '#1890ff',
        permission: 'infra:api-access-log:query',
      },
      {
        key: 'errorLog',
        name: '错误日志',
        icon: 'exclamation-circle',
        url: '/pages-infra/api-error-log/index',
        iconColor: '#f5222d',
        permission: 'infra:api-error-log:query',
      },
      {
        key: 'config',
        name: '参数配置',
        icon: 'settings',
        url: '/pages-infra/config/index',
        iconColor: '#722ed1',
        permission: 'infra:config:query',
      },
      {
        key: 'dataSourceConfig',
        name: '数据源配置',
        icon: 'storage',
        url: '/pages-infra/data-source-config/index',
        iconColor: '#9254de',
        permission: 'infra:data-source-config:query',
      },
      {
        key: 'file',
        name: '文件管理',
        icon: 'folder',
        url: '/pages-infra/file/index',
        iconColor: '#2f54eb',
        permission: 'infra:file:query',
      },
      {
        key: 'websocket',
        name: 'WebSocket',
        icon: 'wifi',
        url: '/pages-infra/web-socket/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'job',
        name: '定时任务',
        icon: 'clock-circle',
        url: '/pages-infra/job/index',
        iconColor: '#fa8c16',
        permission: 'infra:job:query',
      },
      {
        key: 'codegen',
        name: '代码生成',
        icon: 'code',
        url: ONLY_PC_PAGE,
        iconColor: '#52c41a',
      },
      {
        key: 'build',
        name: '表单构建',
        icon: 'edit',
        url: ONLY_PC_PAGE,
        iconColor: '#73d13d',
      },
      {
        key: 'swagger',
        name: 'API 接口',
        icon: 'link',
        url: ONLY_PC_PAGE,
        iconColor: '#95de64',
      },
      {
        key: 'druid',
        name: '监控中心',
        icon: 'dashboard',
        url: ONLY_PC_PAGE,
        iconColor: '#389e0d',
      },
    ],
  },
  {
    key: 'member',
    name: 'MEMBER 会员中心',
    menus: [
      {
        key: 'memberUser',
        name: '会员用户',
        icon: 'user',
        url: '/pages-member/user/index',
        iconColor: '#1890ff',
        permission: 'member:user:query',
      },
      {
        key: 'memberGroup',
        name: '用户分组',
        icon: 'user-group',
        url: '/pages-member/group/index',
        iconColor: '#13c2c2',
        permission: 'member:group:query',
      },
      {
        key: 'memberTag',
        name: '会员标签',
        icon: 'tag',
        url: '/pages-member/tag/index',
        iconColor: '#52c41a',
        permission: 'member:tag:query',
      },
      {
        key: 'memberLevel',
        name: '会员等级',
        icon: 'star',
        url: '/pages-member/level/index',
        iconColor: '#faad14',
        permission: 'member:level:query',
      },
      {
        key: 'memberPointRecord',
        name: '积分记录',
        icon: 'star',
        url: '/pages-member/point/record/index',
        iconColor: '#fa8c16',
        permission: 'point:record:query',
      },
      {
        key: 'memberSignInConfig',
        name: '签到配置',
        icon: 'calendar-line',
        url: '/pages-member/signin/config/index',
        iconColor: '#2f54eb',
        permission: 'point:sign-in-config:query',
      },
      {
        key: 'memberSignInRecord',
        name: '签到记录',
        icon: 'calendar-line',
        url: '/pages-member/signin/record/index',
        iconColor: '#722ed1',
        permission: 'point:sign-in-record:query',
      },
      {
        key: 'memberConfig',
        name: '会员配置',
        icon: 'settings',
        url: '/pages-member/config/index',
        iconColor: '#eb2f96',
        permission: 'member:config:query',
      },
    ],
  },
  {
    key: 'ai',
    name: 'AI 大模型',
    menus: [
      {
        key: 'aiWorkbench',
        name: 'AI 工作台',
        icon: 'message',
        url: '/pages-ai/index/index',
        iconColor: '#1677ff',
      },
      {
        key: 'aiChat',
        name: 'AI 对话',
        icon: 'message',
        url: '/pages-ai/chat/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'aiImage',
        name: 'AI 绘图',
        icon: 'image',
        url: '/pages-ai/image/index',
        iconColor: '#722ed1',
      },
      {
        key: 'aiMusic',
        name: 'AI 音乐',
        icon: 'sound',
        url: '/pages-ai/music/index',
        iconColor: '#f5222d',
      },
      {
        key: 'aiWrite',
        name: 'AI 写作',
        icon: 'edit',
        url: '/pages-ai/write/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'aiMindMap',
        name: '思维导图',
        icon: 'share-alt',
        url: '/pages-ai/mindmap/index',
        iconColor: '#52c41a',
      },
      {
        key: 'aiModel',
        name: '模型配置',
        icon: 'settings',
        url: '/pages-ai/model/index',
        iconColor: '#eb2f96',
        permission: 'ai:model:query',
      },
      {
        key: 'aiKnowledge',
        name: '知识库',
        icon: 'folder',
        url: '/pages-ai/knowledge/index',
        iconColor: '#2f54eb',
        permission: 'ai:knowledge:query',
      },
      {
        key: 'aiContent',
        name: '生成记录',
        icon: 'list',
        url: '/pages-ai/content/index',
        iconColor: '#faad14',
      },
      {
        key: 'aiWorkflow',
        name: 'AI 工作流',
        icon: 'tool',
        url: '/pages-ai/workflow/index',
        iconColor: '#36cfc9',
        permission: 'ai:workflow:query',
      },
    ],
  },
  {
    key: 'crm',
    name: 'CRM 客户管理',
    menus: [
      {
        key: 'crmBacklog',
        name: 'CRM 待办',
        icon: 'calendar-line',
        url: '/pages-crm/backlog/index',
        iconColor: '#fa541c',
      },
      {
        key: 'crmCustomer',
        name: '客户',
        icon: 'user',
        url: '/pages-crm/customer/index',
        iconColor: '#1890ff',
        permission: 'crm:customer:query',
      },
      {
        key: 'crmCustomerPool',
        name: '公海客户',
        icon: 'user-group',
        url: '/pages-crm/customer/pool/index',
        iconColor: '#13c2c2',
        permission: 'crm:customer:query',
      },
      {
        key: 'crmClue',
        name: '线索',
        icon: 'notification',
        url: '/pages-crm/clue/index',
        iconColor: '#13c2c2',
        permission: 'crm:clue:query',
      },
      {
        key: 'crmContact',
        name: '联系人',
        icon: 'user-group',
        url: '/pages-crm/contact/index',
        iconColor: '#52c41a',
        permission: 'crm:contact:query',
      },
      {
        key: 'crmBusiness',
        name: '商机',
        icon: 'dashboard',
        url: '/pages-crm/business/index',
        iconColor: '#722ed1',
        permission: 'crm:business:query',
      },
      {
        key: 'crmContract',
        name: '合同',
        icon: 'file',
        url: '/pages-crm/contract/index',
        iconColor: '#fa8c16',
        permission: 'crm:contract:query',
      },
      {
        key: 'crmReceivable',
        name: '回款',
        icon: 'store',
        url: '/pages-crm/receivable/index',
        iconColor: '#eb2f96',
        permission: 'crm:receivable:query',
      },
      {
        key: 'crmReceivablePlan',
        name: '回款计划',
        icon: 'calendar-line',
        url: '/pages-crm/receivable-plan/index',
        iconColor: '#faad14',
        permission: 'crm:receivable-plan:query',
      },
      {
        key: 'crmProduct',
        name: '产品',
        icon: 'apps',
        url: '/pages-crm/product/index',
        iconColor: '#2f54eb',
        permission: 'crm:product:query',
      },
      {
        key: 'crmProductCategory',
        name: '产品分类',
        icon: 'folder',
        url: '/pages-crm/product/category/index',
        iconColor: '#36cfc9',
        permission: 'crm:product-category:query',
      },
      {
        key: 'crmBusinessStatus',
        name: '商机状态',
        icon: 'settings',
        url: '/pages-crm/business/status/index',
        iconColor: '#9254de',
        permission: 'crm:business-status:query',
      },
      {
        key: 'crmCustomerLimitConfig',
        name: '客户限制',
        icon: 'settings',
        url: '/pages-crm/customer/limit-config/index',
        iconColor: '#5cdbd3',
        permission: 'crm:customer-limit-config:query',
      },
      {
        key: 'crmCustomerPoolConfig',
        name: '公海规则',
        icon: 'settings',
        url: '/pages-crm/customer/pool-config/index',
        iconColor: '#40a9ff',
        permission: 'crm:customer-pool-config:query',
      },
      {
        key: 'crmContractConfig',
        name: '合同提醒',
        icon: 'settings',
        url: '/pages-crm/contract/config/index',
        iconColor: '#ffc53d',
        permission: 'crm:contract-config:query',
      },
      {
        key: 'crmStatisticsCustomer',
        name: '客户统计',
        icon: 'dashboard',
        url: '/pages-statistics/crm/customer/index',
        iconColor: '#1677ff',
        permission: 'crm:statistics-customer:query',
      },
      {
        key: 'crmStatisticsFunnel',
        name: '销售漏斗',
        icon: 'dashboard',
        url: '/pages-statistics/crm/funnel/index',
        iconColor: '#722ed1',
        permission: 'crm:statistics-funnel:query',
      },
      {
        key: 'crmStatisticsPerformance',
        name: '员工业绩',
        icon: 'dashboard',
        url: '/pages-statistics/crm/performance/index',
        iconColor: '#52c41a',
        permission: 'crm:statistics-performance:query',
      },
      {
        key: 'crmStatisticsPortrait',
        name: '客户画像',
        icon: 'dashboard',
        url: '/pages-statistics/crm/portrait/index',
        iconColor: '#eb2f96',
        permission: 'crm:statistics-portrait:query',
      },
      {
        key: 'crmStatisticsRank',
        name: '排行榜',
        icon: 'dashboard',
        url: '/pages-statistics/crm/rank/index',
        iconColor: '#faad14',
        permission: 'crm:statistics-rank:query',
      },
    ],
  },
  {
    key: 'iot',
    name: 'IoT 物联网',
    menus: [
      {
        key: 'iotHome',
        name: 'IoT 工作台',
        icon: 'dashboard',
        url: '/pages-iot/home/index',
        iconColor: '#1677ff',
      },
      {
        key: 'iotProduct',
        name: '产品管理',
        icon: 'apps',
        url: '/pages-iot/product/product/index',
        iconColor: '#2f54eb',
        permission: 'iot:product:query',
      },
      {
        key: 'iotProductCategory',
        name: '产品分类',
        icon: 'folder',
        url: '/pages-iot/product/category/index',
        iconColor: '#13c2c2',
        permission: 'iot:product-category:query',
      },
      {
        key: 'iotDevice',
        name: '设备管理',
        icon: 'wifi',
        url: '/pages-iot/device/device/index',
        iconColor: '#52c41a',
        permission: 'iot:device:query',
      },
      {
        key: 'iotDeviceGroup',
        name: '设备分组',
        icon: 'folder',
        url: '/pages-iot/device/group/index',
        iconColor: '#73d13d',
        permission: 'iot:device-group:query',
      },
      {
        key: 'iotThingModel',
        name: '产品物模型',
        icon: 'list',
        url: '/pages-iot/thingmodel/index',
        iconColor: '#722ed1',
        permission: 'iot:thing-model:query',
      },
      {
        key: 'iotAlertConfig',
        name: '告警配置',
        icon: 'notification',
        url: '/pages-iot/alert/config/index',
        iconColor: '#fa8c16',
        permission: 'iot:alert-config:query',
      },
      {
        key: 'iotAlertRecord',
        name: '告警记录',
        icon: 'exclamation-circle',
        url: '/pages-iot/alert/record/index',
        iconColor: '#f5222d',
        permission: 'iot:alert-record:query',
      },
      {
        key: 'iotOtaFirmware',
        name: 'OTA 固件',
        icon: 'upload',
        url: '/pages-iot/ota/firmware/index',
        iconColor: '#faad14',
        permission: 'iot:ota-firmware:query',
      },
      {
        key: 'iotOtaTask',
        name: 'OTA 任务',
        icon: 'clock-circle',
        url: '/pages-iot/ota/task/index',
        iconColor: '#ffc53d',
        permission: 'iot:ota-task:query',
      },
      {
        key: 'iotDataSink',
        name: '数据目的',
        icon: 'link',
        url: '/pages-iot/rule/data/sink/index',
        iconColor: '#eb2f96',
        permission: 'iot:data-sink:query',
      },
      {
        key: 'iotDataRule',
        name: '数据规则',
        icon: 'code',
        url: '/pages-iot/rule/data/rule/index',
        iconColor: '#f759ab',
        permission: 'iot:data-rule:query',
      },
      {
        key: 'iotSceneRule',
        name: '场景联动',
        icon: 'sound',
        url: '/pages-iot/rule/scene/index',
        iconColor: '#5cdbd3',
        permission: 'iot:scene-rule:query',
      },
    ],
  },
  {
    key: 'mp',
    name: 'MP 微信公众号',
    menus: [
      {
        key: 'mpAccount',
        name: '账号',
        icon: 'user-group',
        url: '/pages-mp/account/index',
        iconColor: '#07c160',
        permission: 'mp:account:query',
      },
      {
        key: 'mpTag',
        name: '标签',
        icon: 'tag',
        url: '/pages-mp/tag/index',
        iconColor: '#13c2c2',
        permission: 'mp:tag:query',
      },
      {
        key: 'mpUser',
        name: '粉丝',
        icon: 'user',
        url: '/pages-mp/user/index',
        iconColor: '#1890ff',
        permission: 'mp:user:query',
      },
      {
        key: 'mpMenu',
        name: '菜单',
        icon: 'settings',
        url: '/pages-mp/menu/index',
        iconColor: '#2f54eb',
        permission: 'mp:menu:query',
      },
      {
        key: 'mpAutoReply',
        name: '自动回复',
        icon: 'reply',
        url: '/pages-mp/auto-reply/index',
        iconColor: '#722ed1',
        permission: 'mp:auto-reply:query',
      },
      {
        key: 'mpMessage',
        name: '消息',
        icon: 'email',
        url: '/pages-mp/message/index',
        iconColor: '#fa8c16',
        permission: 'mp:message:query',
      },
      {
        key: 'mpMessageTemplate',
        name: '模板',
        icon: 'notification',
        url: '/pages-mp/message-template/index',
        iconColor: '#eb2f96',
        permission: 'mp:message-template:query',
      },
      {
        key: 'mpMaterial',
        name: '素材',
        icon: 'image',
        url: '/pages-mp/material/index',
        iconColor: '#52c41a',
        permission: 'mp:material:query',
      },
      {
        key: 'mpDraft',
        name: '草稿',
        icon: 'edit',
        url: '/pages-mp/draft/index',
        iconColor: '#faad14',
        permission: 'mp:draft:query',
      },
      {
        key: 'mpFreePublish',
        name: '发表',
        icon: 'share-alt',
        url: '/pages-mp/free-publish/index',
        iconColor: '#36cfc9',
        permission: 'mp:free-publish:query',
      },
      {
        key: 'mpStatistics',
        name: '统计',
        icon: 'dashboard',
        url: '/pages-mp/statistics/index',
        iconColor: '#9254de',
        permission: 'mp:statistics:query',
      },
    ],
  },
  {
    key: 'bpm',
    name: 'BPM 工作流程',
    menus: [
      {
        key: 'bpmMy',
        name: '我的流程',
        icon: 'user',
        url: '/pages/bpm/index?tab=my',
        iconColor: '#1890ff',
        permission: 'bpm:process-instance:query',
      },
      {
        key: 'bpmTodo',
        name: '待办任务',
        icon: 'clock-circle',
        url: '/pages/bpm/index?tab=todo',
        iconColor: '#fa8c16',
        permission: 'bpm:task:query',
      },
      {
        key: 'bpmDone',
        name: '已办任务',
        icon: 'check-circle',
        url: '/pages/bpm/index?tab=done',
        iconColor: '#52c41a',
        permission: 'bpm:task:query',
      },
      {
        key: 'bpmCopy',
        name: '抄送我的',
        icon: 'email',
        url: '/pages/bpm/index?tab=copy',
        iconColor: '#13c2c2',
        permission: 'bpm:process-instance-cc:query',
      },
      {
        key: 'oaLeave',
        name: '请假申请',
        icon: 'calendar-line',
        url: '/pages-bpm/oa/leave/index',
        iconColor: '#52c41a',
        permission: 'bpm:oa-leave:query',
      },
      {
        key: 'bpmModel',
        name: '流程模型',
        icon: 'apps',
        url: ONLY_PC_PAGE,
        iconColor: '#722ed1',
        permission: 'bpm:process-definition:query',
      },
      {
        key: 'bpmForm',
        name: '流程表单',
        icon: 'edit',
        url: ONLY_PC_PAGE,
        iconColor: '#9254de',
        permission: 'bpm:form:query',
      },
      {
        key: 'bpmCategory',
        name: '流程分类',
        icon: 'folder',
        url: '/pages-bpm/category/index',
        iconColor: '#faad14',
        permission: 'bpm:category:query',
      },
      {
        key: 'bpmUserGroup',
        name: '用户分组',
        icon: 'user-group',
        url: '/pages-bpm/user-group/index',
        iconColor: '#ffc53d',
        permission: 'bpm:user-group:query',
      },
      {
        key: 'bpmProcessListener',
        name: '流程监听器',
        icon: 'sound',
        url: '/pages-bpm/process-listener/index',
        iconColor: '#eb2f96',
        permission: 'bpm:process-listener:query',
      },
      {
        key: 'bpmProcessExpression',
        name: '流程表达式',
        icon: 'code',
        url: '/pages-bpm/process-expression/index',
        iconColor: '#f759ab',
        permission: 'bpm:process-expression:query',
      },
      {
        key: 'bpmProcessInstanceManager',
        name: '流程实例',
        icon: 'list',
        url: '/pages-bpm/processInstance/manager/index',
        iconColor: '#36cfc9',
        permission: 'bpm:process-instance:manager-query',
      },
      {
        key: 'bpmTaskManager',
        name: '流程任务',
        icon: 'unordered-list',
        url: '/pages-bpm/task/manager/index',
        iconColor: '#5cdbd3',
        permission: 'bpm:task:manager-query',
      },
    ],
  },
  {
    key: 'mesMd',
    name: 'MES 基础数据',
    menus: [
      {
        key: 'mesHome',
        name: 'MES 工作台',
        icon: 'dashboard',
        url: '/pages-mes/home/index',
        iconColor: '#1677ff',
      },
      {
        key: 'mesMdAutocode',
        name: '编码规则',
        icon: 'code',
        url: '/pages-mes/md/autocode/index',
        iconColor: '#2f54eb',
      },
      {
        key: 'mesMdClient',
        name: '客户管理',
        icon: 'user',
        url: '/pages-mes/md/client/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'mesMdVendor',
        name: '供应商管理',
        icon: 'user-group',
        url: '/pages-mes/md/vendor/index',
        iconColor: '#52c41a',
      },
      {
        key: 'mesMdItem',
        name: '物料产品',
        icon: 'archive',
        url: '/pages-mes/md/item/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'mesMdItemType',
        name: '物料分类',
        icon: 'folder',
        url: '/pages-mes/md/item/type/index',
        iconColor: '#faad14',
      },
      {
        key: 'mesMdUnitmeasure',
        name: '计量单位',
        icon: 'apps',
        url: '/pages-mes/md/unitmeasure/index',
        iconColor: '#722ed1',
      },
      {
        key: 'mesMdWorkshop',
        name: '车间管理',
        icon: 'home',
        url: '/pages-mes/md/workstation/workshop/index',
        iconColor: '#eb2f96',
      },
      {
        key: 'mesMdWorkstation',
        name: '工作站',
        icon: 'location',
        url: '/pages-mes/md/workstation/index',
        iconColor: '#36cfc9',
      },
    ],
  },
  {
    key: 'mesPro',
    name: 'MES 生产管理',
    menus: [
      {
        key: 'mesProWorkorder',
        name: '生产工单',
        icon: 'ordered-list',
        url: '/pages-mes/pro/workorder/index',
        iconColor: '#52c41a',
      },
      {
        key: 'mesProTask',
        name: '生产排产',
        icon: 'calendar-line',
        url: '/pages-mes/pro/task/index',
        iconColor: '#73d13d',
      },
      {
        key: 'mesProFeedback',
        name: '生产报工',
        icon: 'edit',
        url: '/pages-mes/pro/feedback/index',
        iconColor: '#95de64',
      },
      {
        key: 'mesProProcess',
        name: '生产工序',
        icon: 'settings',
        url: '/pages-mes/pro/process/index',
        iconColor: '#389e0d',
      },
      {
        key: 'mesProRoute',
        name: '工艺路线',
        icon: 'share-alt',
        url: '/pages-mes/pro/route/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'mesProCard',
        name: '流转卡',
        icon: 'idcard',
        url: '/pages-mes/pro/card/index',
        iconColor: '#1677ff',
      },
      {
        key: 'mesProAndonRecord',
        name: '安灯记录',
        icon: 'exclamation-circle',
        url: '/pages-mes/pro/andon/record/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'mesProWorkrecord',
        name: '工作记录',
        icon: 'list',
        url: '/pages-mes/pro/workrecord/index',
        iconColor: '#722ed1',
      },
    ],
  },
  {
    key: 'mesWm',
    name: 'MES 仓储管理',
    menus: [
      {
        key: 'mesWmArrivalnotice',
        name: '到货通知',
        icon: 'notification',
        url: '/pages-mes/wm/arrivalnotice/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'mesWmItemreceipt',
        name: '采购入库',
        icon: 'download',
        url: '/pages-mes/wm/itemreceipt/index',
        iconColor: '#faad14',
      },
      {
        key: 'mesWmReturnvendor',
        name: '采购退货',
        icon: 'undo',
        url: '/pages-mes/wm/returnvendor/index',
        iconColor: '#ff7a45',
      },
      {
        key: 'mesWmMaterialstock',
        name: '库存台账',
        icon: 'dashboard',
        url: '/pages-mes/wm/materialstock/index',
        iconColor: '#722ed1',
      },
      {
        key: 'mesWmMiscreceipt',
        name: '其他入库',
        icon: 'download',
        url: '/pages-mes/wm/miscreceipt/index',
        iconColor: '#52c41a',
      },
      {
        key: 'mesWmMiscissue',
        name: '其他出库',
        icon: 'upload',
        url: '/pages-mes/wm/miscissue/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'mesWmOutsourceissue',
        name: '外协发料',
        icon: 'upload',
        url: '/pages-mes/wm/outsourceissue/index',
        iconColor: '#2f54eb',
      },
      {
        key: 'mesWmOutsourcereceipt',
        name: '外协入库',
        icon: 'download',
        url: '/pages-mes/wm/outsourcereceipt/index',
        iconColor: '#597ef7',
      },
      {
        key: 'mesWmProductissue',
        name: '生产领料',
        icon: 'upload',
        url: '/pages-mes/wm/productissue/index',
        iconColor: '#9254de',
      },
      {
        key: 'mesWmReturnissue',
        name: '生产退料',
        icon: 'undo',
        url: '/pages-mes/wm/returnissue/index',
        iconColor: '#eb2f96',
      },
      {
        key: 'mesWmProductreceipt',
        name: '产品入库',
        icon: 'download',
        url: '/pages-mes/wm/productreceipt/index',
        iconColor: '#36cfc9',
      },
      {
        key: 'mesWmProductsales',
        name: '销售出库',
        icon: 'upload',
        url: '/pages-mes/wm/productsales/index',
        iconColor: '#f759ab',
      },
      {
        key: 'mesWmReturnsales',
        name: '销售退货',
        icon: 'undo',
        url: '/pages-mes/wm/returnsales/index',
        iconColor: '#ff85c0',
      },
      {
        key: 'mesWmSalesnotice',
        name: '发货通知',
        icon: 'send',
        url: '/pages-mes/wm/salesnotice/index',
        iconColor: '#5cdbd3',
      },
      {
        key: 'mesWmTransfer',
        name: '库存调拨',
        icon: 'swap',
        url: '/pages-mes/wm/transfer/index',
        iconColor: '#87e8de',
      },
      {
        key: 'mesWmPackages',
        name: '装箱单',
        icon: 'archive',
        url: '/pages-mes/wm/packages/index',
        iconColor: '#ffc53d',
      },
      {
        key: 'mesWmSn',
        name: 'SN 码',
        icon: 'code',
        url: '/pages-mes/wm/sn/index',
        iconColor: '#1677ff',
      },
      {
        key: 'mesWmBarcode',
        name: '条码管理',
        icon: 'code',
        url: '/pages-mes/wm/barcode/index',
        iconColor: '#1890ff',
      },
      {
        key: 'mesWmBarcodeConfig',
        name: '条码配置',
        icon: 'settings',
        url: '/pages-mes/wm/barcode/config/index',
        iconColor: '#2f54eb',
      },
      {
        key: 'mesWmStocktakingPlan',
        name: '盘点方案',
        icon: 'calendar-line',
        url: '/pages-mes/wm/stocktaking/plan/index',
        iconColor: '#722ed1',
      },
      {
        key: 'mesWmStocktakingTask',
        name: '盘点任务',
        icon: 'check-circle',
        url: '/pages-mes/wm/stocktaking/task/index',
        iconColor: '#52c41a',
      },
      {
        key: 'mesWmWarehouse',
        name: '仓库管理',
        icon: 'home',
        url: '/pages-mes/wm/warehouse/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'mesWmWarehouseArea',
        name: '库区管理',
        icon: 'folder',
        url: '/pages-mes/wm/warehouse/area/index',
        iconColor: '#faad14',
      },
      {
        key: 'mesWmWarehouseLocation',
        name: '库位管理',
        icon: 'location',
        url: '/pages-mes/wm/warehouse/location/index',
        iconColor: '#13c2c2',
      },
    ],
  },
  {
    key: 'mesQc',
    name: 'MES 质量管理',
    menus: [
      {
        key: 'mesQcTemplate',
        name: '质检方案',
        icon: 'safe',
        url: '/pages-mes/qc/template/index',
        iconColor: '#722ed1',
      },
      {
        key: 'mesQcIndicator',
        name: '质检指标',
        icon: 'list',
        url: '/pages-mes/qc/indicator/index',
        iconColor: '#9254de',
      },
      {
        key: 'mesQcDefect',
        name: '缺陷类型',
        icon: 'exclamation-circle',
        url: '/pages-mes/qc/defect/index',
        iconColor: '#f5222d',
      },
      {
        key: 'mesQcPendinginspect',
        name: '待检任务',
        icon: 'clock-circle',
        url: '/pages-mes/qc/pendinginspect/index',
        iconColor: '#fa8c16',
      },
      {
        key: 'mesQcIqc',
        name: '来料检验',
        icon: 'check-circle',
        url: '/pages-mes/qc/iqc/index',
        iconColor: '#52c41a',
      },
      {
        key: 'mesQcIpqc',
        name: '过程检验',
        icon: 'check-circle',
        url: '/pages-mes/qc/ipqc/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'mesQcOqc',
        name: '出货检验',
        icon: 'check-circle',
        url: '/pages-mes/qc/oqc/index',
        iconColor: '#2f54eb',
      },
      {
        key: 'mesQcRqc',
        name: '退货检验',
        icon: 'undo',
        url: '/pages-mes/qc/rqc/index',
        iconColor: '#eb2f96',
      },
      {
        key: 'mesQcBatchtrace',
        name: '批次追溯',
        icon: 'share-alt',
        url: '/pages-mes/qc/batchtrace/index',
        iconColor: '#36cfc9',
      },
    ],
  },
  {
    key: 'mesDv',
    name: 'MES 设备管理',
    menus: [
      {
        key: 'mesDvMachinery',
        name: '设备台账',
        icon: 'tool',
        url: '/pages-mes/dv/machinery/index',
        iconColor: '#13c2c2',
      },
      {
        key: 'mesDvMachineryType',
        name: '设备类型',
        icon: 'folder',
        url: '/pages-mes/dv/machinery/type/index',
        iconColor: '#36cfc9',
      },
      {
        key: 'mesDvSubject',
        name: '点检项目',
        icon: 'list',
        url: '/pages-mes/dv/subject/index',
        iconColor: '#2f54eb',
      },
      {
        key: 'mesDvCheckplan',
        name: '点检方案',
        icon: 'calendar-line',
        url: '/pages-mes/dv/checkplan/index',
        iconColor: '#722ed1',
      },
      {
        key: 'mesDvCheckrecord',
        name: '点检记录',
        icon: 'check-circle',
        url: '/pages-mes/dv/checkrecord/index',
        iconColor: '#52c41a',
      },
      {
        key: 'mesDvMaintenrecord',
        name: '保养记录',
        icon: 'settings',
        url: '/pages-mes/dv/maintenrecord/index',
        iconColor: '#faad14',
      },
      {
        key: 'mesDvRepair',
        name: '维修工单',
        icon: 'edit',
        url: '/pages-mes/dv/repair/index',
        iconColor: '#fa8c16',
      },
    ],
  },
  {
    key: 'mesCal',
    name: 'MES 排班管理',
    menus: [
      {
        key: 'mesCalCalendar',
        name: '排班日历',
        icon: 'calendar-line',
        url: '/pages-mes/cal/calendar/index',
        iconColor: '#eb2f96',
      },
      {
        key: 'mesCalPlan',
        name: '排班计划',
        icon: 'calendar-line',
        url: '/pages-mes/cal/plan/index',
        iconColor: '#f759ab',
      },
      {
        key: 'mesCalTeam',
        name: '班组设置',
        icon: 'user-group',
        url: '/pages-mes/cal/team/index',
        iconColor: '#722ed1',
      },
      {
        key: 'mesCalHoliday',
        name: '假期设置',
        icon: 'clock-circle',
        url: '/pages-mes/cal/holiday/index',
        iconColor: '#fa8c16',
      },
    ],
  },
  {
    key: 'mesTm',
    name: 'MES 工具管理',
    menus: [
      {
        key: 'mesTmTool',
        name: '工具台账',
        icon: 'tool',
        url: '/pages-mes/tm/tool/index',
        iconColor: '#faad14',
      },
      {
        key: 'mesTmToolType',
        name: '工具类型',
        icon: 'folder',
        url: '/pages-mes/tm/tool/type/index',
        iconColor: '#ffc53d',
      },
    ],
  },
  {
    key: 'pay',
    name: 'PAY 支付管理',
    menus: [
      {
        key: 'payApp',
        name: '支付应用',
        icon: 'apps',
        url: '/pages-pay/index?tab=app',
        iconColor: '#fa8c16',
        permission: 'pay:app:query',
      },
      {
        key: 'payOrder',
        name: '支付订单',
        icon: 'ordered-list',
        url: '/pages-pay/index?tab=order',
        iconColor: '#faad14',
        permission: 'pay:order:query',
      },
      {
        key: 'payRefund',
        name: '退款订单',
        icon: 'refresh',
        url: '/pages-pay/index?tab=refund',
        iconColor: '#f5222d',
        permission: 'pay:refund:query',
      },
      {
        key: 'payNotify',
        name: '支付通知',
        icon: 'notification',
        url: '/pages-pay/index?tab=notify',
        iconColor: '#722ed1',
        permission: 'pay:notify:query',
      },
      {
        key: 'payTransfer',
        name: '转账订单',
        icon: 'send',
        url: '/pages-pay/index?tab=transfer',
        iconColor: '#2f54eb',
        permission: 'pay:transfer:query',
      },
      {
        key: 'payWallet',
        name: '钱包余额',
        icon: 'safe',
        url: '/pages-pay/index?tab=wallet',
        iconColor: '#13c2c2',
        permission: 'pay:wallet:query',
      },
      {
        key: 'payRechargePackage',
        name: '充值套餐',
        icon: 'archive',
        url: '/pages-pay/index?tab=recharge-package',
        iconColor: '#52c41a',
        permission: 'pay:wallet-recharge-package:query',
      },
      {
        key: 'payWalletTransaction',
        name: '钱包流水',
        icon: 'list',
        url: '/pages-pay/index?tab=wallet-transaction',
        iconColor: '#36cfc9',
        permission: 'pay:wallet:query',
      },
      {
        key: 'payDemoOrder',
        name: '示例订单',
        icon: 'ordered-list',
        url: '/pages-pay/demo/order/index',
        iconColor: '#eb2f96',
      },
      {
        key: 'payDemoWithdraw',
        name: '示例提现',
        icon: 'safe',
        url: '/pages-pay/demo/withdraw/index',
        iconColor: '#fa541c',
      },
    ],
  },
  {
    key: 'mall',
    name: 'MALL 商城管理',
    menus: [
      {
        key: 'mallHome',
        name: '商城工作台',
        icon: 'dashboard',
        url: '/pages-mall/index',
        iconColor: '#1677ff',
      },
      {
        key: 'mallProductSpu',
        name: '商品管理',
        icon: 'archive',
        url: '/pages-mall/resource/index?resource=productSpu',
        iconColor: '#13c2c2',
        permission: 'product:spu:query',
      },
      {
        key: 'mallProductBrand',
        name: '品牌管理',
        icon: 'store',
        url: '/pages-mall/resource/index?resource=productBrand',
        iconColor: '#52c41a',
        permission: 'product:brand:query',
      },
      {
        key: 'mallProductCategory',
        name: '商品分类',
        icon: 'apps',
        url: '/pages-mall/resource/index?resource=productCategory',
        iconColor: '#faad14',
        permission: 'product:category:query',
      },
      {
        key: 'mallTradeOrder',
        name: '订单管理',
        icon: 'ordered-list',
        url: '/pages-mall/resource/index?resource=tradeOrder',
        iconColor: '#fa8c16',
        permission: 'trade:order:query',
      },
      {
        key: 'mallTradeAfterSale',
        name: '售后管理',
        icon: 'refresh',
        url: '/pages-mall/resource/index?resource=tradeAfterSale',
        iconColor: '#f5222d',
        permission: 'trade:after-sale:query',
      },
      {
        key: 'mallDeliveryExpress',
        name: '快递公司',
        icon: 'send',
        url: '/pages-mall/resource/index?resource=deliveryExpress',
        iconColor: '#2f54eb',
        permission: 'trade:delivery:express:query',
      },
      {
        key: 'mallPromotionBanner',
        name: 'Banner',
        icon: 'image',
        url: '/pages-mall/resource/index?resource=promotionBanner',
        iconColor: '#722ed1',
        permission: 'promotion:banner:query',
      },
      {
        key: 'mallPromotionArticle',
        name: '文章管理',
        icon: 'edit',
        url: '/pages-mall/resource/index?resource=promotionArticle',
        iconColor: '#eb2f96',
        permission: 'promotion:article:query',
      },
      {
        key: 'mallProductProperty',
        name: '商品属性',
        icon: 'list',
        url: '/pages-mall/resource/index?resource=productProperty',
        iconColor: '#08979c',
        permission: 'product:property:query',
      },
      {
        key: 'mallProductPropertyValue',
        name: '属性值',
        icon: 'list',
        url: '/pages-mall/resource/index?resource=productPropertyValue',
        iconColor: '#006d75',
        permission: 'product:property:query',
      },
      {
        key: 'mallProductComment',
        name: '商品评论',
        icon: 'message',
        url: '/pages-mall/resource/index?resource=productComment',
        iconColor: '#fa541c',
        permission: 'product:comment:query',
      },
      {
        key: 'mallProductFavorite',
        name: '商品收藏',
        icon: 'star',
        url: '/pages-mall/resource/index?resource=productFavorite',
        iconColor: '#faad14',
        permission: 'product:favorite:query',
      },
      {
        key: 'mallProductBrowseHistory',
        name: '浏览记录',
        icon: 'history',
        url: '/pages-mall/resource/index?resource=productBrowseHistory',
        iconColor: '#d46b08',
        permission: 'product:browse-history:query',
      },
      {
        key: 'mallDeliveryExpressTemplate',
        name: '运费模板',
        icon: 'file',
        url: '/pages-mall/resource/index?resource=deliveryExpressTemplate',
        iconColor: '#2f54eb',
        permission: 'trade:delivery:express-template:query',
      },
      {
        key: 'mallDeliveryPickUpStore',
        name: '自提门店',
        icon: 'store',
        url: '/pages-mall/resource/index?resource=deliveryPickUpStore',
        iconColor: '#13c2c2',
        permission: 'trade:delivery:pick-up-store:query',
      },
      {
        key: 'mallDeliveryPickUpOrder',
        name: '核销订单',
        icon: 'scan',
        url: '/pages-mall/resource/index?resource=deliveryPickUpOrder',
        iconColor: '#36cfc9',
        permission: 'trade:order:query',
      },
      {
        key: 'mallTradeConfig',
        name: '交易配置',
        icon: 'settings',
        url: '/pages-mall/trade/config/index',
        iconColor: '#597ef7',
        permission: 'trade:config:query',
      },
      {
        key: 'mallBrokerageUser',
        name: '分销用户',
        icon: 'user',
        url: '/pages-mall/resource/index?resource=brokerageUser',
        iconColor: '#722ed1',
        permission: 'trade:brokerage-user:query',
      },
      {
        key: 'mallBrokerageRecord',
        name: '佣金记录',
        icon: 'list',
        url: '/pages-mall/resource/index?resource=brokerageRecord',
        iconColor: '#9254de',
        permission: 'trade:brokerage-record:query',
      },
      {
        key: 'mallBrokerageWithdraw',
        name: '佣金提现',
        icon: 'safe',
        url: '/pages-mall/resource/index?resource=brokerageWithdraw',
        iconColor: '#531dab',
        permission: 'trade:brokerage-withdraw:query',
      },
      {
        key: 'mallPromotionArticleCategory',
        name: '文章分类',
        icon: 'folder',
        url: '/pages-mall/resource/index?resource=promotionArticleCategory',
        iconColor: '#c41d7f',
        permission: 'promotion:article-category:query',
      },
      {
        key: 'mallPromotionCouponTemplate',
        name: '券模板',
        icon: 'tags',
        url: '/pages-mall/resource/index?resource=promotionCouponTemplate',
        iconColor: '#eb2f96',
        permission: 'promotion:coupon-template:query',
      },
      {
        key: 'mallPromotionCoupon',
        name: '优惠券',
        icon: 'tags',
        url: '/pages-mall/resource/index?resource=promotionCoupon',
        iconColor: '#f759ab',
        permission: 'promotion:coupon:query',
      },
      {
        key: 'mallPromotionDiscountActivity',
        name: '限时折扣',
        icon: 'tag',
        url: '/pages-mall/resource/index?resource=promotionDiscountActivity',
        iconColor: '#f5222d',
        permission: 'promotion:discount-activity:query',
      },
      {
        key: 'mallPromotionRewardActivity',
        name: '满减送',
        icon: 'gift',
        url: '/pages-mall/resource/index?resource=promotionRewardActivity',
        iconColor: '#fa541c',
        permission: 'promotion:reward-activity:query',
      },
      {
        key: 'mallPromotionSeckillActivity',
        name: '秒杀活动',
        icon: 'clock-circle',
        url: '/pages-mall/resource/index?resource=promotionSeckillActivity',
        iconColor: '#fa8c16',
        permission: 'promotion:seckill-activity:query',
      },
      {
        key: 'mallPromotionSeckillConfig',
        name: '秒杀时段',
        icon: 'time-line',
        url: '/pages-mall/resource/index?resource=promotionSeckillConfig',
        iconColor: '#faad14',
        permission: 'promotion:seckill-config:query',
      },
      {
        key: 'mallPromotionCombinationActivity',
        name: '拼团活动',
        icon: 'user-group',
        url: '/pages-mall/resource/index?resource=promotionCombinationActivity',
        iconColor: '#52c41a',
        permission: 'promotion:combination-activity:query',
      },
      {
        key: 'mallPromotionCombinationRecord',
        name: '拼团记录',
        icon: 'list',
        url: '/pages-mall/resource/index?resource=promotionCombinationRecord',
        iconColor: '#389e0d',
        permission: 'promotion:combination-record:query',
      },
      {
        key: 'mallPromotionBargainActivity',
        name: '砍价活动',
        icon: 'scissor',
        url: '/pages-mall/resource/index?resource=promotionBargainActivity',
        iconColor: '#13c2c2',
        permission: 'promotion:bargain-activity:query',
      },
      {
        key: 'mallPromotionBargainRecord',
        name: '砍价记录',
        icon: 'list',
        url: '/pages-mall/resource/index?resource=promotionBargainRecord',
        iconColor: '#08979c',
        permission: 'promotion:bargain-record:query',
      },
      {
        key: 'mallPromotionPointActivity',
        name: '积分商城',
        icon: 'star',
        url: '/pages-mall/resource/index?resource=promotionPointActivity',
        iconColor: '#1677ff',
        permission: 'promotion:point-activity:query',
      },
      {
        key: 'mallPromotionDiyPage',
        name: '装修页面',
        icon: 'layout',
        url: '/pages-mall/resource/index?resource=promotionDiyPage',
        iconColor: '#2f54eb',
        permission: 'promotion:diy-page:query',
      },
      {
        key: 'mallPromotionDiyTemplate',
        name: '装修模板',
        icon: 'copy',
        url: '/pages-mall/resource/index?resource=promotionDiyTemplate',
        iconColor: '#597ef7',
        permission: 'promotion:diy-template:query',
      },
      {
        key: 'mallKefu',
        name: '客服会话',
        icon: 'message',
        url: '/pages-mall/kefu/index',
        iconColor: '#722ed1',
        permission: 'promotion:kefu-conversation:query',
      },
      {
        key: 'mallStatisticsTrade',
        name: '交易统计',
        icon: 'dashboard',
        url: '/pages-mall/statistics/index?type=trade',
        iconColor: '#fa8c16',
      },
      {
        key: 'mallStatisticsProduct',
        name: '商品统计',
        icon: 'dashboard',
        url: '/pages-mall/statistics/index?type=product',
        iconColor: '#52c41a',
      },
      {
        key: 'mallStatisticsMember',
        name: '会员统计',
        icon: 'dashboard',
        url: '/pages-mall/statistics/index?type=member',
        iconColor: '#1677ff',
      },
    ],
  },
  {
    key: 'wms',
    name: 'WMS 仓储管理',
    menus: [
      {
        key: 'wmsHome',
        name: 'WMS 工作台',
        icon: 'dashboard',
        url: '/pages-wms/home/index',
        iconColor: '#1677ff',
        permission: 'wms:home:query',
      },
      {
        key: 'wmsWarehouse',
        name: '仓库管理',
        icon: 'home',
        url: '/pages-wms/md/warehouse/index',
        iconColor: '#13c2c2',
        permission: 'wms:warehouse:query',
      },
      {
        key: 'wmsMerchant',
        name: '往来企业',
        icon: 'user-group',
        url: '/pages-wms/md/merchant/index',
        iconColor: '#52c41a',
        permission: 'wms:merchant:query',
      },
      {
        key: 'wmsItemCategory',
        name: '商品分类',
        icon: 'folder',
        url: '/pages-wms/md/item/category/index',
        iconColor: '#faad14',
        permission: 'wms:item-category:query',
      },
      {
        key: 'wmsItemBrand',
        name: '商品品牌',
        icon: 'store',
        url: '/pages-wms/md/item/brand/index',
        iconColor: '#fa8c16',
        permission: 'wms:item-brand:query',
      },
      {
        key: 'wmsItem',
        name: '商品管理',
        icon: 'archive',
        url: '/pages-wms/md/item/index',
        iconColor: '#f5222d',
        permission: 'wms:item:query',
      },
      {
        key: 'wmsInventory',
        name: '库存统计',
        icon: 'dashboard',
        url: '/pages-wms/inventory/index',
        iconColor: '#722ed1',
        permission: 'wms:inventory:query',
      },
      {
        key: 'wmsInventoryHistory',
        name: '库存流水',
        icon: 'list',
        url: '/pages-wms/inventory/history/index',
        iconColor: '#9254de',
        permission: 'wms:inventory-history:query',
      },
      {
        key: 'wmsReceiptOrder',
        name: '入库单',
        icon: 'download',
        url: '/pages-wms/order/receipt/index',
        iconColor: '#36cfc9',
        permission: 'wms:receipt-order:query',
      },
      {
        key: 'wmsShipmentOrder',
        name: '出库单',
        icon: 'upload',
        url: '/pages-wms/order/shipment/index',
        iconColor: '#13c2c2',
        permission: 'wms:shipment-order:query',
      },
      {
        key: 'wmsMovementOrder',
        name: '移库单',
        icon: 'swap',
        url: '/pages-wms/order/movement/index',
        iconColor: '#5cdbd3',
        permission: 'wms:movement-order:query',
      },
      {
        key: 'wmsCheckOrder',
        name: '盘库单',
        icon: 'check-circle',
        url: '/pages-wms/order/check/index',
        iconColor: '#87e8de',
        permission: 'wms:check-order:query',
      },
    ],
  },
  {
    key: 'erp',
    name: 'ERP 管理',
    menus: [
      {
        key: 'erpOverview',
        name: 'ERP 概览',
        icon: 'dashboard',
        url: '/pages-erp/index',
        iconColor: '#1677ff',
      },
      {
        key: 'erpProductCategory',
        name: '产品分类',
        icon: 'folder',
        url: '/pages-erp/crud/index?module=product-category',
        iconColor: '#13c2c2',
        permission: 'erp:product-category:query',
      },
      {
        key: 'erpProduct',
        name: '产品管理',
        icon: 'apps',
        url: '/pages-erp/crud/index?module=product',
        iconColor: '#1890ff',
        permission: 'erp:product:query',
      },
      {
        key: 'erpProductUnit',
        name: '产品单位',
        icon: 'apps',
        url: '/pages-erp/crud/index?module=product-unit',
        iconColor: '#2f54eb',
        permission: 'erp:product-unit:query',
      },
      {
        key: 'erpSupplier',
        name: '供应商',
        icon: 'user-group',
        url: '/pages-erp/crud/index?module=supplier',
        iconColor: '#fa8c16',
        permission: 'erp:supplier:query',
      },
      {
        key: 'erpPurchaseOrder',
        name: '采购订单',
        icon: 'ordered-list',
        url: '/pages-erp/crud/index?module=purchase-order',
        iconColor: '#faad14',
        permission: 'erp:purchase-order:query',
      },
      {
        key: 'erpPurchaseIn',
        name: '采购入库',
        icon: 'download',
        url: '/pages-erp/crud/index?module=purchase-in',
        iconColor: '#ffc53d',
        permission: 'erp:purchase-in:query',
      },
      {
        key: 'erpPurchaseReturn',
        name: '采购退货',
        icon: 'undo',
        url: '/pages-erp/crud/index?module=purchase-return',
        iconColor: '#ff7a45',
        permission: 'erp:purchase-return:query',
      },
      {
        key: 'erpCustomer',
        name: '客户',
        icon: 'user',
        url: '/pages-erp/crud/index?module=customer',
        iconColor: '#52c41a',
        permission: 'erp:customer:query',
      },
      {
        key: 'erpSaleOrder',
        name: '销售订单',
        icon: 'ordered-list',
        url: '/pages-erp/crud/index?module=sale-order',
        iconColor: '#73d13d',
        permission: 'erp:sale-order:query',
      },
      {
        key: 'erpSaleOut',
        name: '销售出库',
        icon: 'upload',
        url: '/pages-erp/crud/index?module=sale-out',
        iconColor: '#95de64',
        permission: 'erp:sale-out:query',
      },
      {
        key: 'erpSaleReturn',
        name: '销售退货',
        icon: 'undo',
        url: '/pages-erp/crud/index?module=sale-return',
        iconColor: '#389e0d',
        permission: 'erp:sale-return:query',
      },
      {
        key: 'erpWarehouse',
        name: '仓库管理',
        icon: 'home',
        url: '/pages-erp/crud/index?module=warehouse',
        iconColor: '#722ed1',
        permission: 'erp:warehouse:query',
      },
      {
        key: 'erpStock',
        name: '产品库存',
        icon: 'dashboard',
        url: '/pages-erp/crud/index?module=stock',
        iconColor: '#9254de',
        permission: 'erp:stock:query',
      },
      {
        key: 'erpStockRecord',
        name: '库存明细',
        icon: 'list',
        url: '/pages-erp/crud/index?module=stock-record',
        iconColor: '#597ef7',
        permission: 'erp:stock-record:query',
      },
      {
        key: 'erpStockIn',
        name: '其它入库',
        icon: 'download',
        url: '/pages-erp/crud/index?module=stock-in',
        iconColor: '#36cfc9',
        permission: 'erp:stock-in:query',
      },
      {
        key: 'erpStockOut',
        name: '其它出库',
        icon: 'upload',
        url: '/pages-erp/crud/index?module=stock-out',
        iconColor: '#13c2c2',
        permission: 'erp:stock-out:query',
      },
      {
        key: 'erpStockMove',
        name: '库存调拨',
        icon: 'swap',
        url: '/pages-erp/crud/index?module=stock-move',
        iconColor: '#5cdbd3',
        permission: 'erp:stock-move:query',
      },
      {
        key: 'erpStockCheck',
        name: '库存盘点',
        icon: 'check-circle',
        url: '/pages-erp/crud/index?module=stock-check',
        iconColor: '#87e8de',
        permission: 'erp:stock-check:query',
      },
      {
        key: 'erpAccount',
        name: '结算账户',
        icon: 'safe',
        url: '/pages-erp/crud/index?module=account',
        iconColor: '#eb2f96',
        permission: 'erp:account:query',
      },
      {
        key: 'erpFinancePayment',
        name: '付款单',
        icon: 'safe',
        url: '/pages-erp/crud/index?module=finance-payment',
        iconColor: '#f759ab',
        permission: 'erp:finance-payment:query',
      },
      {
        key: 'erpFinanceReceipt',
        name: '收款单',
        icon: 'safe',
        url: '/pages-erp/crud/index?module=finance-receipt',
        iconColor: '#ff85c0',
        permission: 'erp:finance-receipt:query',
      },
    ],
  },
]

/** 全局菜单分组展示顺序 */
// TODO @AI：排序，是不是上面配置的时候，有个顺序就行了？不用单独搞个数组把。。。
const GROUP_ORDER = [
  'system', // 系统管理
  'infra', // 基础设施
  'bpm', // 工作流程
  // CRM / ERP / MES / WMS
  'crm',
  'erp',
  'mesMd',
  'mesPro',
  'mesWm',
  'mesQc',
  'mesDv',
  'mesCal',
  'mesTm',
  'wms',
  // 物联网 / AI / IM
  'iot',
  'ai',
  'im',
  // 公众号 / 支付 / 会员 / 商城
  'mp',
  'pay',
  'member',
  'mall',
]

/** 分组内菜单展示顺序（未列出的分组保持原顺序） */
const MENU_ORDER: Record<string, string[]> = {
  crm: [
    // 业务
    'crmBacklog',
    'crmClue',
    'crmCustomer',
    'crmContact',
    'crmCustomerPool',
    'crmBusiness',
    'crmContract',
    'crmReceivable',
    'crmReceivablePlan',
    'crmProduct',
    // 数据统计
    'crmStatisticsCustomer',
    'crmStatisticsFunnel',
    'crmStatisticsPerformance',
    'crmStatisticsPortrait',
    'crmStatisticsRank',
    // 系统配置
    'crmProductCategory',
    'crmBusinessStatus',
    'crmCustomerLimitConfig',
    'crmCustomerPoolConfig',
    'crmContractConfig',
  ],
}

/** 取在顺序数组中的下标，未列出的排到最后 */
function orderIndex(order: string[], key: string) {
  const index = order.indexOf(key)
  return index === -1 ? order.length : index
}

/**
 * 获取所有菜单分组数据（带权限过滤）：过滤掉没有权限的菜单项，如果整个分组都没有权限则不展示该分组
 */
export function getMenuGroups(): MenuGroup[] {
  const { hasAccessByCodes } = useAccess()
  return menuGroupsData
    .map((group) => {
      // 过滤掉没有权限的菜单项
      const menus = group.menus.filter((menu) => {
        // 没有配置权限的菜单项默认展示
        if (!menu.permission) {
          return true
        }
        return hasAccessByCodes([menu.permission])
      })
      // 分组内菜单按配置顺序排序
      const order = MENU_ORDER[group.key]
      if (order) {
        menus.sort((a, b) => orderIndex(order, a.key) - orderIndex(order, b.key))
      }
      return { ...group, menus }
    })
    // 过滤掉没有菜单项的分组
    .filter(group => group.menus.length > 0)
    // 按全局顺序排序
    .sort((a, b) => GROUP_ORDER.indexOf(a.key) - GROUP_ORDER.indexOf(b.key))
}

/** 获取所有菜单项（扁平化） */
export function getAllMenuItems(): MenuItem[] {
  const groups = getMenuGroups()
  return groups.flatMap(group => group.menus)
}

/** 根据 key 获取菜单项 */
export function getMenuItemByKey(key: string): MenuItem | undefined {
  return getAllMenuItems().find(item => item.key === key)
}
