import type { PageParam, PageResult } from '@/http/types'
import type { MallResourceConfig, MallResourceGroup } from './types'
import {
  createProductBrand,
  deleteProductBrand,
  getProductBrand,
  getProductBrandPage,
  getSimpleProductBrandList,
  updateProductBrand,
} from '@/api/mall/product/brand'
import {
  createProductCategory,
  deleteProductCategory,
  getProductCategory,
  getProductCategoryList,
  updateProductCategory,
} from '@/api/mall/product/category'
import {
  createProductSpu,
  deleteProductSpu,
  getProductSpu,
  getProductSpuPage,
  getSimpleProductSpuList,
  updateProductSpu,
} from '@/api/mall/product/spu'
import {
  createProductProperty,
  deleteProductProperty,
  getProductProperty,
  getProductPropertyPage,
  updateProductProperty,
} from '@/api/mall/product/property'
import {
  getProductComment,
  getProductCommentPage,
  replyProductComment,
  updateProductCommentVisible,
} from '@/api/mall/product/comment'
import {
  deliveryTradeOrder,
  getTradeOrder,
  getTradeOrderPage,
  pickUpTradeOrder,
  updateTradeOrderAddress,
  updateTradeOrderPrice,
  updateTradeOrderRemark,
} from '@/api/mall/trade/order'
import {
  agreeTradeAfterSale,
  disagreeTradeAfterSale,
  getTradeAfterSale,
  getTradeAfterSalePage,
  receiveTradeAfterSale,
  refundTradeAfterSale,
  refuseTradeAfterSale,
} from '@/api/mall/trade/after-sale'
import {
  createDeliveryExpress,
  deleteDeliveryExpress,
  getDeliveryExpress,
  getDeliveryExpressPage,
  updateDeliveryExpress,
} from '@/api/mall/trade/delivery/express'
import { getSimpleDeliveryExpressTemplateList } from '@/api/mall/trade/delivery/express-template'
import {
  createPromotionBanner,
  deletePromotionBanner,
  getPromotionBanner,
  getPromotionBannerPage,
  updatePromotionBanner,
} from '@/api/mall/promotion/banner'
import {
  createPromotionArticleCategory,
  deletePromotionArticleCategory,
  getPromotionArticleCategory,
  getPromotionArticleCategoryPage,
  getSimplePromotionArticleCategoryList,
  updatePromotionArticleCategory,
} from '@/api/mall/promotion/article-category'
import {
  createPromotionArticle,
  deletePromotionArticle,
  getPromotionArticle,
  getPromotionArticlePage,
  updatePromotionArticle,
} from '@/api/mall/promotion/article'
import { CommonStatusEnum, DICT_TYPE } from '@/utils/constants'
import { cleanMallQuery, createLocalMallPage, toMallOptions } from './utils'
import { mallExtraResourceConfigs, mallExtraResourceGroups } from './extra-config'

/** 商城资源分组 */
export const mallResourceGroups: MallResourceGroup[] = [
  {
    key: 'product',
    name: '商品中心',
    resources: ['productSpu', 'productBrand', 'productCategory', 'productProperty', 'productComment'],
  },
  {
    key: 'trade',
    name: '交易中心',
    resources: ['tradeOrder', 'tradeAfterSale', 'deliveryExpress'],
  },
  {
    key: 'promotion',
    name: '营销中心',
    resources: ['promotionBanner', 'promotionArticle', 'promotionArticleCategory'],
  },
  ...mallExtraResourceGroups,
]

/** 本地列表转分页 */
async function createCategoryPage(params: PageParam): Promise<PageResult<Record<string, any>>> {
  const query = { ...params }
  delete query.pageNo
  delete query.pageSize
  const list = await getProductCategoryList(cleanMallQuery(query))
  return createLocalMallPage(
    [...list].sort((a, b) => (a.sort || 0) - (b.sort || 0)),
    params,
  )
}

/** 商城资源配置 */
const mallResourceConfigs: Record<string, MallResourceConfig> = {
  productSpu: {
    key: 'productSpu',
    module: 'product',
    title: '商品管理',
    emptyText: '暂无商品数据',
    permissions: {
      query: 'product:spu:query',
      create: 'product:spu:create',
      update: 'product:spu:update',
      delete: 'product:spu:delete',
    },
    page: params => getProductSpuPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getProductSpu(id) as Promise<Record<string, any>>,
    create: data => createProductSpu(data as any),
    update: data => updateProductSpu(data as any),
    delete: deleteProductSpu,
    listTitle: row => row.name || '-',
    listSubtitle: row => row.introduction || row.keyword || '暂无简介',
    listImage: row => row.picUrl,
    formUrl: id => `/pages-mall/product/spu/form/index${id ? `?id=${id}` : ''}`,
    statusField: { prop: 'status', label: '商品状态', dictType: DICT_TYPE.PRODUCT_SPU_STATUS },
    searchFields: [
      { prop: 'name', label: '商品名称', type: 'text' },
      { prop: 'status', label: '商品状态', type: 'dict', dictType: DICT_TYPE.PRODUCT_SPU_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'price', label: '销售价', type: 'money' },
      { prop: 'stock', label: '库存', type: 'number' },
      { prop: 'salesCount', label: '销量', type: 'number' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'name', label: '商品名称' },
      { prop: 'categoryName', label: '商品分类' },
      { prop: 'brandName', label: '商品品牌' },
      { prop: 'keyword', label: '关键字' },
      { prop: 'price', label: '销售价', type: 'money' },
      { prop: 'marketPrice', label: '市场价', type: 'money' },
      { prop: 'costPrice', label: '成本价', type: 'money' },
      { prop: 'stock', label: '库存', type: 'number' },
      { prop: 'salesCount', label: '销量', type: 'number' },
      { prop: 'virtualSalesCount', label: '虚拟销量', type: 'number' },
      { prop: 'status', label: '商品状态', type: 'dict', dictType: DICT_TYPE.PRODUCT_SPU_STATUS },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
      { prop: 'introduction', label: '商品简介', type: 'textarea' },
      { prop: 'description', label: '商品详情', type: 'textarea' },
    ],
    formFields: [
      { prop: 'name', label: '商品名称', type: 'text', required: true },
      {
        prop: 'categoryId',
        label: '商品分类',
        type: 'picker',
        required: true,
        loadOptions: async () => toMallOptions(await getProductCategoryList()),
      },
      {
        prop: 'brandId',
        label: '商品品牌',
        type: 'picker',
        loadOptions: async () => toMallOptions(await getSimpleProductBrandList()),
      },
      { prop: 'keyword', label: '关键字', type: 'text' },
      { prop: 'unit', label: '单位编号', type: 'number' },
      { prop: 'picUrl', label: '商品封面', type: 'image', required: true },
      { prop: 'sliderPicUrls', label: '轮播图 URL', type: 'array', required: true },
      { prop: 'introduction', label: '商品简介', type: 'textarea' },
      { prop: 'deliveryTypes', label: '配送方式', type: 'array', arrayValueType: 'number', required: true },
      {
        prop: 'deliveryTemplateId',
        label: '运费模板',
        type: 'picker',
        loadOptions: async () => toMallOptions(await getSimpleDeliveryExpressTemplateList()),
      },
      { prop: 'specType', label: '多规格', type: 'boolean', required: true },
      { prop: 'subCommissionType', label: '单独分佣', type: 'boolean', required: true },
      { prop: 'skus', label: 'SKU JSON', type: 'json', required: true },
      { prop: 'description', label: '商品详情', type: 'textarea', required: true },
      { prop: 'sort', label: '排序', type: 'number', required: true },
      { prop: 'giveIntegral', label: '赠送积分', type: 'number' },
      { prop: 'virtualSalesCount', label: '虚拟销量', type: 'number' },
      { prop: 'status', label: '商品状态', type: 'dict', dictType: DICT_TYPE.PRODUCT_SPU_STATUS, required: true },
    ],
    defaultForm: () => ({
      id: undefined,
      name: '',
      categoryId: undefined,
      brandId: undefined,
      keyword: '',
      unit: 1,
      picUrl: '',
      sliderPicUrls: '',
      introduction: '',
      deliveryTypes: '1',
      deliveryTemplateId: undefined,
      specType: false,
      subCommissionType: false,
      skus: '[{"price":0,"marketPrice":0,"costPrice":0,"stock":0}]',
      description: '',
      sort: 0,
      giveIntegral: 0,
      virtualSalesCount: 0,
      status: 0,
    }),
  },
  productBrand: {
    key: 'productBrand',
    module: 'product',
    title: '品牌管理',
    emptyText: '暂无品牌数据',
    permissions: {
      query: 'product:brand:query',
      create: 'product:brand:create',
      update: 'product:brand:update',
      delete: 'product:brand:delete',
    },
    page: params => getProductBrandPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getProductBrand(id) as Promise<Record<string, any>>,
    create: data => createProductBrand(data as any),
    update: data => updateProductBrand(data as any),
    delete: deleteProductBrand,
    listTitle: row => row.name || '-',
    listSubtitle: row => row.description || '暂无品牌描述',
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS },
    searchFields: [
      { prop: 'name', label: '品牌名称', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'name', label: '品牌名称' },
      { prop: 'picUrl', label: '品牌图片', type: 'image' },
      { prop: 'sort', label: '品牌排序', type: 'number' },
      { prop: 'status', label: '品牌状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS },
      { prop: 'description', label: '品牌描述', type: 'textarea' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      { prop: 'name', label: '品牌名称', type: 'text', required: true },
      { prop: 'picUrl', label: '品牌图片', type: 'image', required: true },
      { prop: 'sort', label: '品牌排序', type: 'number', required: true, min: 0 },
      { prop: 'status', label: '品牌状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
      { prop: 'description', label: '品牌描述', type: 'textarea' },
    ],
    defaultForm: () => ({
      id: undefined,
      name: '',
      picUrl: '',
      sort: 0,
      status: CommonStatusEnum.ENABLE,
      description: '',
    }),
  },
  productCategory: {
    key: 'productCategory',
    module: 'product',
    title: '商品分类',
    emptyText: '暂无分类数据',
    permissions: {
      query: 'product:category:query',
      create: 'product:category:create',
      update: 'product:category:update',
      delete: 'product:category:delete',
    },
    page: createCategoryPage,
    detail: id => getProductCategory(id) as Promise<Record<string, any>>,
    create: data => createProductCategory(data as any),
    update: data => updateProductCategory(data as any),
    delete: deleteProductCategory,
    listTitle: row => row.name || '-',
    listSubtitle: row => `上级分类：${row.parentId || 0}`,
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS },
    searchFields: [
      { prop: 'name', label: '分类名称', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'parentId', label: '父级编号', type: 'number' },
      { prop: 'sort', label: '排序', type: 'number' },
    ],
    detailFields: [
      { prop: 'name', label: '分类名称' },
      { prop: 'parentId', label: '上级分类', type: 'number' },
      { prop: 'picUrl', label: '分类图片', type: 'image' },
      { prop: 'sort', label: '分类排序', type: 'number' },
      { prop: 'status', label: '开启状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      {
        prop: 'parentId',
        label: '上级分类',
        type: 'picker',
        required: true,
        loadOptions: async () => [
          { label: '顶级分类', value: 0 },
          ...toMallOptions(await getProductCategoryList({ parentId: 0 })),
        ],
      },
      { prop: 'name', label: '分类名称', type: 'text', required: true },
      { prop: 'picUrl', label: '分类图片', type: 'image', required: true },
      { prop: 'sort', label: '分类排序', type: 'number', required: true, min: 0 },
      { prop: 'status', label: '开启状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
    ],
    defaultForm: () => ({
      id: undefined,
      parentId: 0,
      name: '',
      picUrl: '',
      sort: 0,
      status: CommonStatusEnum.ENABLE,
    }),
  },
  productProperty: {
    key: 'productProperty',
    module: 'product',
    title: '商品属性',
    emptyText: '暂无属性数据',
    permissions: {
      query: 'product:property:query',
      create: 'product:property:create',
      update: 'product:property:update',
      delete: 'product:property:delete',
    },
    page: params => getProductPropertyPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getProductProperty(id) as Promise<Record<string, any>>,
    create: data => createProductProperty(data as any),
    update: data => updateProductProperty(data as any),
    delete: deleteProductProperty,
    listTitle: row => row.name || '-',
    listSubtitle: row => row.remark || '暂无备注',
    searchFields: [
      { prop: 'name', label: '属性名称', type: 'text' },
    ],
    cardFields: [
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'name', label: '属性名称' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      { prop: 'name', label: '属性名称', type: 'text', required: true },
      { prop: 'remark', label: '备注', type: 'textarea' },
    ],
    defaultForm: () => ({
      id: undefined,
      name: '',
      remark: '',
    }),
  },
  productComment: {
    key: 'productComment',
    module: 'product',
    title: '商品评论',
    emptyText: '暂无评论数据',
    permissions: {
      query: 'product:comment:query',
    },
    page: params => getProductCommentPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getProductComment(id) as Promise<Record<string, any>>,
    listTitle: row => row.spuName || row.content || '-',
    listSubtitle: row => row.userNickname || '匿名用户',
    listImage: row => row.userAvatar,
    statusField: { prop: 'visible', label: '是否显示', type: 'boolean' },
    searchFields: [
      { prop: 'userNickname', label: '用户昵称', type: 'text' },
      { prop: 'spuName', label: '商品名称', type: 'text' },
      { prop: 'visible', label: '是否显示', type: 'boolean', defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'scores', label: '评分', type: 'number' },
      { prop: 'replyStatus', label: '是否回复', type: 'boolean' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'userNickname', label: '用户昵称' },
      { prop: 'spuName', label: '商品名称' },
      { prop: 'scores', label: '评分', type: 'number' },
      { prop: 'visible', label: '是否显示', type: 'boolean' },
      { prop: 'content', label: '评论内容', type: 'textarea' },
      { prop: 'replyStatus', label: '是否回复', type: 'boolean' },
      { prop: 'replyContent', label: '回复内容', type: 'textarea' },
      { prop: 'replyTime', label: '回复时间', type: 'datetime' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    actions: [
      {
        key: 'reply',
        label: '商家回复',
        type: 'primary',
        permission: 'product:comment:update',
        fields: [{ prop: 'replyContent', label: '回复内容', type: 'textarea', required: true }],
        defaultForm: row => ({ id: row.id, replyContent: row.replyContent || '' }),
        handler: (row, data) => replyProductComment({ id: Number(row.id), replyContent: String(data?.replyContent || '') }),
        successText: '回复成功',
      },
      {
        key: 'toggle-visible',
        label: '显示/隐藏',
        type: 'warning',
        permission: 'product:comment:update',
        confirm: row => row.visible ? '确定要隐藏该评论吗？' : '确定要显示该评论吗？',
        handler: row => updateProductCommentVisible({ id: Number(row.id), visible: !row.visible }),
        successText: '操作成功',
      },
    ],
  },
  tradeOrder: {
    key: 'tradeOrder',
    module: 'trade',
    title: '订单管理',
    emptyText: '暂无订单数据',
    permissions: {
      query: 'trade:order:query',
    },
    page: params => getTradeOrderPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getTradeOrder(id) as Promise<Record<string, any>>,
    listTitle: row => row.no || '-',
    listSubtitle: row => row.user?.nickname || row.receiverName || '暂无用户信息',
    listImage: row => row.user?.avatar || row.items?.[0]?.picUrl,
    detailUrl: id => `/pages-mall/trade/order/detail/index?id=${id}`,
    statusField: { prop: 'status', label: '订单状态', dictType: DICT_TYPE.TRADE_ORDER_STATUS },
    searchFields: [
      { prop: 'no', label: '订单号', type: 'text' },
      { prop: 'status', label: '订单状态', type: 'dict', dictType: DICT_TYPE.TRADE_ORDER_STATUS, defaultValue: -1 },
      { prop: 'deliveryType', label: '配送方式', type: 'dict', dictType: DICT_TYPE.TRADE_DELIVERY_TYPE, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'payPrice', label: '实付金额', type: 'money' },
      { prop: 'productCount', label: '商品数量', type: 'number' },
      { prop: 'payStatus', label: '是否支付', type: 'boolean' },
      { prop: 'createTime', label: '下单时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'no', label: '订单号' },
      { prop: 'status', label: '订单状态', type: 'dict', dictType: DICT_TYPE.TRADE_ORDER_STATUS },
      { prop: 'type', label: '订单类型', type: 'dict', dictType: DICT_TYPE.TRADE_ORDER_TYPE },
      { prop: 'terminal', label: '订单来源', type: 'dict', dictType: DICT_TYPE.TERMINAL },
      { prop: 'user.nickname', label: '下单用户' },
      { prop: 'productCount', label: '商品数量', type: 'number' },
      { prop: 'totalPrice', label: '商品原价', type: 'money' },
      { prop: 'discountPrice', label: '优惠金额', type: 'money' },
      { prop: 'deliveryPrice', label: '运费金额', type: 'money' },
      { prop: 'adjustPrice', label: '订单调价', type: 'money' },
      { prop: 'payPrice', label: '实付金额', type: 'money' },
      { prop: 'payStatus', label: '是否支付', type: 'boolean' },
      { prop: 'payTime', label: '付款时间', type: 'datetime' },
      { prop: 'deliveryType', label: '配送方式', type: 'dict', dictType: DICT_TYPE.TRADE_DELIVERY_TYPE },
      { prop: 'receiverName', label: '收件人' },
      { prop: 'receiverMobile', label: '收件手机' },
      { prop: 'receiverAreaName', label: '收件地区' },
      { prop: 'receiverDetailAddress', label: '详细地址', type: 'textarea' },
      { prop: 'remark', label: '商家备注', type: 'textarea' },
      { prop: 'createTime', label: '下单时间', type: 'datetime' },
    ],
    actions: [
      {
        key: 'delivery',
        label: '订单发货',
        type: 'primary',
        permission: 'trade:order:update',
        fields: [
          { prop: 'logisticsId', label: '快递公司编号', type: 'number' },
          { prop: 'logisticsNo', label: '快递单号', type: 'text', required: true },
        ],
        defaultForm: row => ({ id: row.id, logisticsId: row.logisticsId, logisticsNo: row.logisticsNo || '' }),
        handler: (row, data) => deliveryTradeOrder({ id: Number(row.id), logisticsId: data?.logisticsId ?? null, logisticsNo: String(data?.logisticsNo || '') }),
        successText: '发货成功',
      },
      {
        key: 'remark',
        label: '修改备注',
        type: 'warning',
        permission: 'trade:order:update',
        fields: [{ prop: 'remark', label: '商家备注', type: 'textarea', required: true }],
        defaultForm: row => ({ id: row.id, remark: row.remark || '' }),
        handler: (row, data) => updateTradeOrderRemark({ id: row.id, remark: data?.remark }),
        successText: '备注已更新',
      },
      {
        key: 'price',
        label: '订单改价',
        type: 'warning',
        permission: 'trade:order:update',
        fields: [
          { prop: 'adjustPrice', label: '订单调价', type: 'money', min: -999999, required: true, placeholder: '正数加价，负数减价' },
        ],
        defaultForm: row => ({ id: row.id, adjustPrice: Number(row.adjustPrice || 0) / 100 }),
        handler: (row, data) => updateTradeOrderPrice({ id: row.id, adjustPrice: data?.adjustPrice }),
        successText: '价格已更新',
      },
      {
        key: 'address',
        label: '修改地址',
        type: 'warning',
        permission: 'trade:order:update',
        fields: [
          { prop: 'receiverName', label: '收件人', type: 'text', required: true },
          { prop: 'receiverMobile', label: '手机号', type: 'text', required: true },
          { prop: 'receiverAreaId', label: '地区编号', type: 'number', required: true },
          { prop: 'receiverDetailAddress', label: '详细地址', type: 'textarea', required: true },
        ],
        defaultForm: row => ({
          id: row.id,
          receiverName: row.receiverName || '',
          receiverMobile: row.receiverMobile || '',
          receiverAreaId: row.receiverAreaId,
          receiverDetailAddress: row.receiverDetailAddress || '',
        }),
        handler: (row, data) => updateTradeOrderAddress({ id: row.id, ...data }),
        successText: '地址已更新',
      },
      {
        key: 'pick-up',
        label: '订单核销',
        type: 'primary',
        permission: 'trade:order:pick-up',
        confirm: '确定要核销该订单吗？',
        handler: row => pickUpTradeOrder(Number(row.id)),
        successText: '核销成功',
      },
    ],
  },
  tradeAfterSale: {
    key: 'tradeAfterSale',
    module: 'trade',
    title: '售后管理',
    emptyText: '暂无售后数据',
    permissions: {
      query: 'trade:after-sale:query',
    },
    page: params => getTradeAfterSalePage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getTradeAfterSale(id) as Promise<Record<string, any>>,
    listTitle: row => row.no || '-',
    listSubtitle: row => row.spuName || row.orderNo || '暂无商品信息',
    listImage: row => row.picUrl,
    detailUrl: id => `/pages-mall/trade/after-sale/detail/index?id=${id}`,
    statusField: { prop: 'status', label: '售后状态', dictType: DICT_TYPE.TRADE_AFTER_SALE_STATUS },
    searchFields: [
      { prop: 'no', label: '售后单号', type: 'text' },
      { prop: 'orderNo', label: '订单号', type: 'text' },
      { prop: 'status', label: '售后状态', type: 'dict', dictType: DICT_TYPE.TRADE_AFTER_SALE_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'refundPrice', label: '退款金额', type: 'money' },
      { prop: 'count', label: '退货数量', type: 'number' },
      { prop: 'createTime', label: '申请时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'no', label: '售后单号' },
      { prop: 'orderNo', label: '订单号' },
      { prop: 'status', label: '售后状态', type: 'dict', dictType: DICT_TYPE.TRADE_AFTER_SALE_STATUS },
      { prop: 'way', label: '售后方式', type: 'dict', dictType: DICT_TYPE.TRADE_AFTER_SALE_WAY },
      { prop: 'type', label: '售后类型', type: 'dict', dictType: DICT_TYPE.TRADE_AFTER_SALE_TYPE },
      { prop: 'spuName', label: '商品名称' },
      { prop: 'picUrl', label: '商品图片', type: 'image' },
      { prop: 'count', label: '退货数量', type: 'number' },
      { prop: 'refundPrice', label: '退款金额', type: 'money' },
      { prop: 'applyReason', label: '申请原因' },
      { prop: 'applyDescription', label: '补充描述', type: 'textarea' },
      { prop: 'auditReason', label: '审批备注', type: 'textarea' },
      { prop: 'logisticsNo', label: '退货物流单号' },
      { prop: 'createTime', label: '申请时间', type: 'datetime' },
    ],
    actions: [
      {
        key: 'agree',
        label: '同意售后',
        type: 'primary',
        permission: 'trade:after-sale:audit',
        confirm: '确定同意该售后申请吗？',
        handler: row => agreeTradeAfterSale(Number(row.id)),
        successText: '已同意',
      },
      {
        key: 'disagree',
        label: '拒绝售后',
        type: 'danger',
        permission: 'trade:after-sale:audit',
        fields: [{ prop: 'auditReason', label: '拒绝原因', type: 'textarea', required: true }],
        defaultForm: row => ({ id: row.id, auditReason: row.auditReason || '' }),
        handler: (row, data) => disagreeTradeAfterSale({ id: row.id, auditReason: data?.auditReason }),
        successText: '已拒绝',
      },
      {
        key: 'receive',
        label: '确认收货',
        type: 'primary',
        permission: 'trade:after-sale:receive',
        confirm: '确定已收到退货吗？',
        handler: row => receiveTradeAfterSale(Number(row.id)),
        successText: '收货成功',
      },
      {
        key: 'refuse',
        label: '拒绝收货',
        type: 'danger',
        permission: 'trade:after-sale:receive',
        confirm: '确定拒绝收货吗？',
        handler: row => refuseTradeAfterSale(Number(row.id)),
        successText: '已拒绝收货',
      },
      {
        key: 'refund',
        label: '确认退款',
        type: 'primary',
        permission: 'trade:after-sale:refund',
        confirm: '确定执行退款吗？',
        handler: row => refundTradeAfterSale(Number(row.id)),
        successText: '退款成功',
      },
    ],
  },
  deliveryExpress: {
    key: 'deliveryExpress',
    module: 'trade',
    title: '快递公司',
    emptyText: '暂无快递公司数据',
    permissions: {
      query: 'trade:delivery:express:query',
      create: 'trade:delivery:express:create',
      update: 'trade:delivery:express:update',
      delete: 'trade:delivery:express:delete',
    },
    page: params => getDeliveryExpressPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getDeliveryExpress(id) as Promise<Record<string, any>>,
    create: data => createDeliveryExpress(data as any),
    update: data => updateDeliveryExpress(data as any),
    delete: deleteDeliveryExpress,
    listTitle: row => row.name || '-',
    listSubtitle: row => row.code || '暂无编码',
    listImage: row => row.logo,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS },
    searchFields: [
      { prop: 'code', label: '公司编码', type: 'text' },
      { prop: 'name', label: '公司名称', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'code', label: '公司编码' },
      { prop: 'name', label: '公司名称' },
      { prop: 'logo', label: '公司 Logo', type: 'image' },
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'status', label: '开启状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      { prop: 'code', label: '公司编码', type: 'text', required: true },
      { prop: 'name', label: '公司名称', type: 'text', required: true },
      { prop: 'logo', label: '公司 Logo', type: 'image', required: true },
      { prop: 'sort', label: '排序', type: 'number', required: true, min: 0 },
      { prop: 'status', label: '开启状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
    ],
    defaultForm: () => ({
      id: undefined,
      code: '',
      name: '',
      logo: '',
      sort: 0,
      status: CommonStatusEnum.ENABLE,
    }),
  },
  promotionBanner: {
    key: 'promotionBanner',
    module: 'promotion',
    title: 'Banner 管理',
    emptyText: '暂无 Banner 数据',
    permissions: {
      query: 'promotion:banner:query',
      create: 'promotion:banner:create',
      update: 'promotion:banner:update',
      delete: 'promotion:banner:delete',
    },
    page: params => getPromotionBannerPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getPromotionBanner(id) as Promise<Record<string, any>>,
    create: data => createPromotionBanner(data as any),
    update: data => updatePromotionBanner(data as any),
    delete: deletePromotionBanner,
    listTitle: row => row.title || '-',
    listSubtitle: row => row.url || '暂无跳转地址',
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS },
    searchFields: [
      { prop: 'title', label: '标题', type: 'text' },
      { prop: 'position', label: '位置', type: 'dict', dictType: DICT_TYPE.PROMOTION_BANNER_POSITION, defaultValue: -1 },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'position', label: '位置', type: 'dict', dictType: DICT_TYPE.PROMOTION_BANNER_POSITION },
      { prop: 'sort', label: '排序', type: 'number' },
    ],
    detailFields: [
      { prop: 'title', label: '标题' },
      { prop: 'picUrl', label: '图片', type: 'image' },
      { prop: 'url', label: '跳转地址' },
      { prop: 'position', label: '位置', type: 'dict', dictType: DICT_TYPE.PROMOTION_BANNER_POSITION },
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS },
      { prop: 'memo', label: '描述', type: 'textarea' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      { prop: 'title', label: '标题', type: 'text', required: true },
      { prop: 'picUrl', label: '图片', type: 'image', required: true },
      { prop: 'url', label: '跳转地址', type: 'text', required: true },
      { prop: 'position', label: '位置', type: 'dict', dictType: DICT_TYPE.PROMOTION_BANNER_POSITION, required: true },
      { prop: 'sort', label: '排序', type: 'number', required: true, min: 0 },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
      { prop: 'memo', label: '描述', type: 'textarea' },
    ],
    defaultForm: () => ({
      id: undefined,
      title: '',
      picUrl: '',
      url: '',
      position: 1,
      sort: 0,
      status: CommonStatusEnum.ENABLE,
      memo: '',
    }),
  },
  promotionArticleCategory: {
    key: 'promotionArticleCategory',
    module: 'promotion',
    title: '文章分类',
    emptyText: '暂无文章分类数据',
    permissions: {
      query: 'promotion:article-category:query',
      create: 'promotion:article-category:create',
      update: 'promotion:article-category:update',
      delete: 'promotion:article-category:delete',
    },
    page: params => getPromotionArticleCategoryPage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getPromotionArticleCategory(id) as Promise<Record<string, any>>,
    create: data => createPromotionArticleCategory(data as any),
    update: data => updatePromotionArticleCategory(data as any),
    delete: deletePromotionArticleCategory,
    listTitle: row => row.name || '-',
    listSubtitle: row => `排序：${row.sort ?? '-'}`,
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS },
    searchFields: [
      { prop: 'name', label: '分类名称', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'name', label: '分类名称' },
      { prop: 'picUrl', label: '分类图片', type: 'image' },
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      { prop: 'name', label: '分类名称', type: 'text', required: true },
      { prop: 'picUrl', label: '分类图片', type: 'image', required: true },
      { prop: 'sort', label: '排序', type: 'number', required: true, min: 0 },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
    ],
    defaultForm: () => ({
      id: undefined,
      name: '',
      picUrl: '',
      sort: 0,
      status: CommonStatusEnum.ENABLE,
    }),
  },
  promotionArticle: {
    key: 'promotionArticle',
    module: 'promotion',
    title: '文章管理',
    emptyText: '暂无文章数据',
    permissions: {
      query: 'promotion:article:query',
      create: 'promotion:article:create',
      update: 'promotion:article:update',
      delete: 'promotion:article:delete',
    },
    page: params => getPromotionArticlePage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getPromotionArticle(id) as Promise<Record<string, any>>,
    create: data => createPromotionArticle(data as any),
    update: data => updatePromotionArticle(data as any),
    delete: deletePromotionArticle,
    listTitle: row => row.title || '-',
    listSubtitle: row => row.introduction || row.author || '暂无简介',
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS },
    searchFields: [
      { prop: 'title', label: '文章标题', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'browseCount', label: '浏览量', type: 'number' },
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'title', label: '文章标题' },
      { prop: 'categoryName', label: '文章分类' },
      { prop: 'author', label: '文章作者' },
      { prop: 'picUrl', label: '文章封面', type: 'image' },
      { prop: 'introduction', label: '文章简介', type: 'textarea' },
      { prop: 'browseCount', label: '浏览量', type: 'number' },
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS },
      { prop: 'recommendHot', label: '是否热门', type: 'boolean' },
      { prop: 'recommendBanner', label: '是否轮播', type: 'boolean' },
      { prop: 'content', label: '文章内容', type: 'textarea' },
      { prop: 'createTime', label: '创建时间', type: 'datetime' },
    ],
    formFields: [
      {
        prop: 'categoryId',
        label: '文章分类',
        type: 'picker',
        required: true,
        loadOptions: async () => toMallOptions(await getSimplePromotionArticleCategoryList()),
      },
      { prop: 'title', label: '文章标题', type: 'text', required: true },
      { prop: 'author', label: '文章作者', type: 'text' },
      { prop: 'picUrl', label: '文章封面', type: 'image', required: true },
      { prop: 'introduction', label: '文章简介', type: 'textarea' },
      { prop: 'sort', label: '排序', type: 'number', required: true, min: 0 },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
      {
        prop: 'spuId',
        label: '关联商品',
        type: 'picker',
        required: true,
        loadOptions: async () => toMallOptions(await getSimpleProductSpuList()),
      },
      { prop: 'recommendHot', label: '是否热门', type: 'boolean', required: true },
      { prop: 'recommendBanner', label: '是否轮播', type: 'boolean', required: true },
      { prop: 'content', label: '文章内容', type: 'textarea', required: true },
    ],
    defaultForm: () => ({
      id: undefined,
      categoryId: undefined,
      title: '',
      author: '',
      picUrl: '',
      introduction: '',
      sort: 0,
      status: CommonStatusEnum.ENABLE,
      spuId: undefined,
      recommendHot: false,
      recommendBanner: false,
      content: '',
    }),
  },
  ...mallExtraResourceConfigs,
}

/** 获取商城资源配置 */
export function getMallResourceConfig(resource?: string) {
  if (!resource) {
    return undefined
  }
  return mallResourceConfigs[resource]
}

/** 获取商城资源配置列表 */
export function getMallResourceConfigs() {
  return Object.values(mallResourceConfigs)
}

/** 获取分组资源 */
export function getMallGroupResources(group: MallResourceGroup) {
  return group.resources.map(key => mallResourceConfigs[key]).filter(Boolean)
}
