import type { PageParam, PageResult } from '@/http/types'
import type { MallResourceConfig, MallResourceField, MallResourceGroup } from './types'
import {
  getProductBrowseHistoryPage,
} from '@/api/mall/product/history'
import { getProductFavoritePage } from '@/api/mall/product/favorite'
import {
  createProductPropertyValue,
  deleteProductPropertyValue,
  getProductPropertyValue,
  getProductPropertyValuePage,
  getSimpleProductPropertyList,
  updateProductPropertyValue,
} from '@/api/mall/product/property'
import {
  createPromotionBargainActivity,
  closePromotionBargainActivity,
  deletePromotionBargainActivity,
  getPromotionBargainActivity,
  getPromotionBargainActivityPage,
  getPromotionBargainHelpPage,
  getPromotionBargainRecordPage,
  updatePromotionBargainActivity,
} from '@/api/mall/promotion/bargain'
import {
  createPromotionCombinationActivity,
  closePromotionCombinationActivity,
  deletePromotionCombinationActivity,
  getPromotionCombinationActivity,
  getPromotionCombinationActivityPage,
  getPromotionCombinationRecordPage,
  updatePromotionCombinationActivity,
} from '@/api/mall/promotion/combination'
import {
  deletePromotionCoupon,
  getPromotionCouponPage,
  sendPromotionCoupon,
} from '@/api/mall/promotion/coupon/coupon'
import {
  createPromotionCouponTemplate,
  deletePromotionCouponTemplate,
  getPromotionCouponTemplate,
  getPromotionCouponTemplatePage,
  updatePromotionCouponTemplate,
  updatePromotionCouponTemplateStatus,
} from '@/api/mall/promotion/coupon/coupon-template'
import {
  createPromotionDiyPage,
  deletePromotionDiyPage,
  getPromotionDiyPage,
  getPromotionDiyPagePage,
  updatePromotionDiyPage,
} from '@/api/mall/promotion/diy/page'
import {
  createPromotionDiyTemplate,
  deletePromotionDiyTemplate,
  getPromotionDiyTemplate,
  getPromotionDiyTemplatePage,
  updatePromotionDiyTemplate,
  usePromotionDiyTemplate,
} from '@/api/mall/promotion/diy/template'
import {
  createPromotionDiscountActivity,
  closePromotionDiscountActivity,
  deletePromotionDiscountActivity,
  getPromotionDiscountActivity,
  getPromotionDiscountActivityPage,
  updatePromotionDiscountActivity,
} from '@/api/mall/promotion/discount'
import {
  createPromotionPointActivity,
  closePromotionPointActivity,
  deletePromotionPointActivity,
  getPromotionPointActivity,
  getPromotionPointActivityPage,
  updatePromotionPointActivity,
} from '@/api/mall/promotion/point'
import {
  createPromotionRewardActivity,
  closePromotionRewardActivity,
  deletePromotionRewardActivity,
  getPromotionRewardActivity,
  getPromotionRewardActivityPage,
  updatePromotionRewardActivity,
} from '@/api/mall/promotion/reward'
import {
  createPromotionSeckillActivity,
  createPromotionSeckillConfig,
  closePromotionSeckillActivity,
  deletePromotionSeckillActivity,
  deletePromotionSeckillConfig,
  getPromotionSeckillActivity,
  getPromotionSeckillActivityPage,
  getPromotionSeckillConfig,
  getPromotionSeckillConfigPage,
  updatePromotionSeckillActivity,
  updatePromotionSeckillConfig,
  updatePromotionSeckillConfigStatus,
} from '@/api/mall/promotion/seckill'
import {
  getTradeBrokerageRecord,
  getTradeBrokerageRecordPage,
} from '@/api/mall/trade/brokerage/record'
import {
  approveTradeBrokerageWithdraw,
  getTradeBrokerageWithdraw,
  getTradeBrokerageWithdrawPage,
  rejectTradeBrokerageWithdraw,
} from '@/api/mall/trade/brokerage/withdraw'
import {
  clearTradeBrokerageUserBind,
  createTradeBrokerageUser,
  getTradeBrokerageUser,
  getTradeBrokerageUserPage,
  updateTradeBrokerageUser,
  updateTradeBrokerageUserEnabled,
} from '@/api/mall/trade/brokerage/user'
import {
  createDeliveryExpressTemplate,
  deleteDeliveryExpressTemplate,
  getDeliveryExpressTemplate,
  getDeliveryExpressTemplatePage,
  updateDeliveryExpressTemplate,
} from '@/api/mall/trade/delivery/express-template'
import { getDeliveryPickUpOrderPage } from '@/api/mall/trade/delivery/pick-up-order'
import {
  bindDeliveryPickUpStoreStaff,
  createDeliveryPickUpStore,
  deleteDeliveryPickUpStore,
  getDeliveryPickUpStore,
  getDeliveryPickUpStorePage,
  updateDeliveryPickUpStore,
} from '@/api/mall/trade/delivery/pick-up-store'
import {
  pickUpTradeOrder,
  pickUpTradeOrderByVerifyCode,
} from '@/api/mall/trade/order'
import { CommonStatusEnum, DICT_TYPE } from '@/utils/constants'
import { toMallOptions } from './utils'

/** 补充资源分组 */
export const mallExtraResourceGroups: MallResourceGroup[] = [
  {
    key: 'product-extra',
    name: '商品扩展',
    resources: ['productPropertyValue', 'productFavorite', 'productBrowseHistory'],
  },
  {
    key: 'trade-extra',
    name: '交易扩展',
    resources: ['deliveryExpressTemplate', 'deliveryPickUpStore', 'deliveryPickUpOrder', 'brokerageUser', 'brokerageRecord', 'brokerageWithdraw'],
  },
  {
    key: 'promotion-extra',
    name: '营销活动',
    resources: [
      'promotionCouponTemplate',
      'promotionCoupon',
      'promotionDiscountActivity',
      'promotionRewardActivity',
      'promotionSeckillActivity',
      'promotionSeckillConfig',
      'promotionCombinationActivity',
      'promotionCombinationRecord',
      'promotionBargainActivity',
      'promotionBargainRecord',
      'promotionBargainHelp',
      'promotionPointActivity',
      'promotionDiyPage',
      'promotionDiyTemplate',
    ],
  },
]

const commonStatusField: MallResourceField = { prop: 'status', label: '状态', dictType: DICT_TYPE.COMMON_STATUS }
const activityStatusField: MallResourceField = { prop: 'status', label: '活动状态', type: 'number' }
const createTimeField: MallResourceField = { prop: 'createTime', label: '创建时间', type: 'datetime' }

/** 透传只读分页 */
function pageOf<T>(request: (params: PageParam) => Promise<PageResult<T>>) {
  return (params: PageParam) => request(params) as Promise<PageResult<Record<string, any>>>
}

/** 本地列表详情 */
function localDetail(page: (params: PageParam) => Promise<PageResult<Record<string, any>>>) {
  return async (id: number) => {
    const data = await page({ pageNo: 1, pageSize: 100 } as PageParam)
    return data.list.find(item => Number(item.id) === Number(id)) || { id }
  }
}

const activityFormFields: MallResourceField[] = [
  { prop: 'name', label: '活动名称', type: 'text', required: true },
  { prop: 'spuId', label: '商品编号', type: 'number', required: true },
  { prop: 'startTime', label: '开始时间', type: 'datetime', required: true },
  { prop: 'endTime', label: '结束时间', type: 'datetime', required: true },
  { prop: 'remark', label: '备注', type: 'textarea' },
  { prop: 'products', label: '商品规则 JSON', type: 'json', required: true },
]

const activityDefault = () => ({
  id: undefined,
  name: '',
  spuId: undefined,
  startTime: '',
  endTime: '',
  remark: '',
  products: '[]',
})

const activityCardFields: MallResourceField[] = [
  { prop: 'startTime', label: '开始时间', type: 'datetime' },
  { prop: 'endTime', label: '结束时间', type: 'datetime' },
  { prop: 'createTime', label: '创建时间', type: 'datetime' },
]

const activityDetailFields: MallResourceField[] = [
  { prop: 'name', label: '活动名称' },
  { prop: 'spuId', label: '商品编号', type: 'number' },
  activityStatusField,
  { prop: 'startTime', label: '开始时间', type: 'datetime' },
  { prop: 'endTime', label: '结束时间', type: 'datetime' },
  { prop: 'remark', label: '备注', type: 'textarea' },
  { prop: 'products', label: '商品规则', type: 'json' },
  createTimeField,
]

/** 活动表单地址 */
const activityFormUrl = (resource: string) => (id?: number) => {
  return `/pages-mall/promotion/activity/form/index?resource=${resource}${id ? `&id=${id}` : ''}`
}

/** 装修表单地址 */
const diyFormUrl = (resource: string) => (id?: number) => {
  return `/pages-mall/promotion/diy/form/index?resource=${resource}${id ? `&id=${id}` : ''}`
}

/** 活动关闭动作 */
function closeAction(handler: (id: number) => Promise<unknown>, permission: string) {
  return {
    key: 'close',
    label: '关闭活动',
    type: 'warning' as const,
    permission,
    confirm: '确定要关闭该活动吗？',
    handler: (row: Record<string, any>) => handler(Number(row.id)),
    successText: '关闭成功',
  }
}

/** 补充资源配置 */
export const mallExtraResourceConfigs: Record<string, MallResourceConfig> = {
  productPropertyValue: {
    key: 'productPropertyValue',
    module: 'product',
    title: '属性值',
    emptyText: '暂无属性值数据',
    permissions: {
      query: 'product:property:query',
      create: 'product:property:create',
      update: 'product:property:update',
      delete: 'product:property:delete',
    },
    page: params => getProductPropertyValuePage(params) as Promise<PageResult<Record<string, any>>>,
    detail: id => getProductPropertyValue(id) as Promise<Record<string, any>>,
    create: data => createProductPropertyValue(data as any),
    update: data => updateProductPropertyValue(data as any),
    delete: deleteProductPropertyValue,
    listTitle: row => row.name || '-',
    listSubtitle: row => `属性编号：${row.propertyId ?? '-'}`,
    searchFields: [
      { prop: 'propertyId', label: '属性编号', type: 'number' },
      { prop: 'name', label: '属性值', type: 'text' },
    ],
    cardFields: [createTimeField],
    detailFields: [
      { prop: 'propertyId', label: '属性编号', type: 'number' },
      { prop: 'name', label: '属性值' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      createTimeField,
    ],
    formFields: [
      {
        prop: 'propertyId',
        label: '属性',
        type: 'picker',
        required: true,
        loadOptions: async () => toMallOptions(await getSimpleProductPropertyList()),
      },
      { prop: 'name', label: '属性值', type: 'text', required: true },
      { prop: 'remark', label: '备注', type: 'textarea' },
    ],
    defaultForm: () => ({ id: undefined, propertyId: undefined, name: '', remark: '' }),
  },
  productFavorite: {
    key: 'productFavorite',
    module: 'product',
    title: '商品收藏',
    emptyText: '暂无收藏数据',
    permissions: { query: 'product:favorite:query' },
    page: pageOf(getProductFavoritePage),
    detail: localDetail(pageOf(getProductFavoritePage)),
    listTitle: row => row.name || `商品 ${row.spuId || '-'}`,
    listSubtitle: row => `用户编号：${row.userId ?? '-'}`,
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '商品状态', dictType: DICT_TYPE.PRODUCT_SPU_STATUS },
    searchFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'spuId', label: '商品编号', type: 'number' },
    ],
    cardFields: [
      { prop: 'price', label: '销售价', type: 'money' },
      { prop: 'salesCount', label: '销量', type: 'number' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'spuId', label: '商品编号', type: 'number' },
      { prop: 'name', label: '商品名称' },
      { prop: 'picUrl', label: '商品图片', type: 'image' },
      { prop: 'price', label: '销售价', type: 'money' },
      { prop: 'status', label: '商品状态', dictType: DICT_TYPE.PRODUCT_SPU_STATUS },
      createTimeField,
    ],
  },
  productBrowseHistory: {
    key: 'productBrowseHistory',
    module: 'product',
    title: '浏览记录',
    emptyText: '暂无浏览记录',
    permissions: { query: 'product:browse-history:query' },
    page: pageOf(getProductBrowseHistoryPage),
    detail: localDetail(pageOf(getProductBrowseHistoryPage)),
    listTitle: row => row.name || `商品 ${row.spuId || '-'}`,
    listSubtitle: row => `用户编号：${row.userId ?? '-'}`,
    listImage: row => row.picUrl,
    statusField: { prop: 'status', label: '商品状态', dictType: DICT_TYPE.PRODUCT_SPU_STATUS },
    searchFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'spuId', label: '商品编号', type: 'number' },
    ],
    cardFields: [
      { prop: 'price', label: '销售价', type: 'money' },
      { prop: 'salesCount', label: '销量', type: 'number' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'spuId', label: '商品编号', type: 'number' },
      { prop: 'name', label: '商品名称' },
      { prop: 'picUrl', label: '商品图片', type: 'image' },
      { prop: 'price', label: '销售价', type: 'money' },
      { prop: 'status', label: '商品状态', dictType: DICT_TYPE.PRODUCT_SPU_STATUS },
      createTimeField,
    ],
  },
  deliveryExpressTemplate: {
    key: 'deliveryExpressTemplate',
    module: 'trade',
    title: '运费模板',
    emptyText: '暂无运费模板数据',
    permissions: {
      query: 'trade:delivery:express-template:query',
      create: 'trade:delivery:express-template:create',
      update: 'trade:delivery:express-template:update',
      delete: 'trade:delivery:express-template:delete',
    },
    page: pageOf(getDeliveryExpressTemplatePage),
    detail: id => getDeliveryExpressTemplate(id) as Promise<Record<string, any>>,
    create: data => createDeliveryExpressTemplate(data as any),
    update: data => updateDeliveryExpressTemplate(data as any),
    delete: deleteDeliveryExpressTemplate,
    listTitle: row => row.name || '-',
    listSubtitle: row => `计费方式：${row.chargeMode ?? '-'}`,
    searchFields: [{ prop: 'name', label: '模板名称', type: 'text' }],
    cardFields: [
      { prop: 'chargeMode', label: '计费方式', type: 'number' },
      { prop: 'sort', label: '排序', type: 'number' },
    ],
    detailFields: [
      { prop: 'name', label: '模板名称' },
      { prop: 'chargeMode', label: '计费方式', type: 'number' },
      { prop: 'sort', label: '排序', type: 'number' },
      { prop: 'templateCharge', label: '计费区域', type: 'json' },
      { prop: 'templateFree', label: '包邮区域', type: 'json' },
      createTimeField,
    ],
    formFields: [
      { prop: 'name', label: '模板名称', type: 'text', required: true },
      { prop: 'chargeMode', label: '计费方式', type: 'number', required: true },
      { prop: 'sort', label: '排序', type: 'number', required: true },
      { prop: 'templateCharge', label: '计费区域 JSON', type: 'json', required: true },
      { prop: 'templateFree', label: '包邮区域 JSON', type: 'json' },
    ],
    defaultForm: () => ({ id: undefined, name: '', chargeMode: 1, sort: 0, templateCharge: '[]', templateFree: '[]' }),
  },
  deliveryPickUpStore: {
    key: 'deliveryPickUpStore',
    module: 'trade',
    title: '自提门店',
    emptyText: '暂无自提门店数据',
    permissions: {
      query: 'trade:delivery:pick-up-store:query',
      create: 'trade:delivery:pick-up-store:create',
      update: 'trade:delivery:pick-up-store:update',
      delete: 'trade:delivery:pick-up-store:delete',
    },
    page: pageOf(getDeliveryPickUpStorePage),
    detail: id => getDeliveryPickUpStore(id) as Promise<Record<string, any>>,
    create: data => createDeliveryPickUpStore(data as any),
    update: data => updateDeliveryPickUpStore(data as any),
    delete: deleteDeliveryPickUpStore,
    listTitle: row => row.name || '-',
    listSubtitle: row => row.phone || row.detailAddress || '暂无门店信息',
    listImage: row => row.logo,
    statusField: commonStatusField,
    searchFields: [
      { prop: 'name', label: '门店名称', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'phone', label: '联系电话' },
      { prop: 'openingTime', label: '营业开始' },
      { prop: 'closingTime', label: '营业结束' },
    ],
    detailFields: [
      { prop: 'name', label: '门店名称' },
      { prop: 'phone', label: '联系电话' },
      { prop: 'logo', label: '门店 Logo', type: 'image' },
      { prop: 'areaId', label: '地区编号', type: 'number' },
      { prop: 'detailAddress', label: '详细地址', type: 'textarea' },
      { prop: 'openingTime', label: '营业开始' },
      { prop: 'closingTime', label: '营业结束' },
      { prop: 'latitude', label: '纬度', type: 'number' },
      { prop: 'longitude', label: '经度', type: 'number' },
      { prop: 'verifyUserIds', label: '核销员编号', type: 'array' },
      commonStatusField,
      createTimeField,
    ],
    formFields: [
      { prop: 'name', label: '门店名称', type: 'text', required: true },
      { prop: 'phone', label: '联系电话', type: 'text', required: true },
      { prop: 'logo', label: '门店 Logo', type: 'image' },
      { prop: 'areaId', label: '地区编号', type: 'number', required: true },
      { prop: 'detailAddress', label: '详细地址', type: 'textarea', required: true },
      { prop: 'openingTime', label: '营业开始', type: 'text', required: true },
      { prop: 'closingTime', label: '营业结束', type: 'text', required: true },
      { prop: 'latitude', label: '纬度', type: 'number' },
      { prop: 'longitude', label: '经度', type: 'number' },
      { prop: 'verifyUserIds', label: '核销员编号', type: 'array', arrayValueType: 'number' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
      { prop: 'introduction', label: '简介', type: 'textarea' },
    ],
    defaultForm: () => ({
      id: undefined,
      name: '',
      phone: '',
      logo: '',
      areaId: undefined,
      detailAddress: '',
      openingTime: '09:00',
      closingTime: '18:00',
      latitude: undefined,
      longitude: undefined,
      verifyUserIds: '',
      status: CommonStatusEnum.ENABLE,
      introduction: '',
    }),
    actions: [
      {
        key: 'bind-staff',
        label: '绑定核销员',
        type: 'primary',
        permission: 'trade:delivery:pick-up-store:update',
        fields: [{ prop: 'verifyUserIds', label: '核销员编号', type: 'array', arrayValueType: 'number', required: true }],
        defaultForm: row => ({ id: row.id, verifyUserIds: Array.isArray(row.verifyUserIds) ? row.verifyUserIds.join(',') : '' }),
        handler: (row, data) => bindDeliveryPickUpStoreStaff({ id: row.id, ...data }),
        successText: '绑定成功',
      },
    ],
  },
  deliveryPickUpOrder: {
    key: 'deliveryPickUpOrder',
    module: 'trade',
    title: '核销订单',
    emptyText: '暂无核销订单数据',
    permissions: { query: 'trade:order:query' },
    page: pageOf(getDeliveryPickUpOrderPage),
    detail: localDetail(pageOf(getDeliveryPickUpOrderPage)),
    listTitle: row => row.no || '-',
    listSubtitle: row => row.user?.nickname || row.receiverName || '暂无用户信息',
    listImage: row => row.items?.[0]?.picUrl,
    statusField: { prop: 'status', label: '订单状态', dictType: DICT_TYPE.TRADE_ORDER_STATUS },
    searchFields: [
      { prop: 'no', label: '订单号', type: 'text' },
      { prop: 'status', label: '订单状态', type: 'dict', dictType: DICT_TYPE.TRADE_ORDER_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'payPrice', label: '实付金额', type: 'money' },
      { prop: 'pickUpVerifyCode', label: '核销码' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'no', label: '订单号' },
      { prop: 'status', label: '订单状态', dictType: DICT_TYPE.TRADE_ORDER_STATUS },
      { prop: 'payPrice', label: '实付金额', type: 'money' },
      { prop: 'pickUpStoreId', label: '自提门店', type: 'number' },
      { prop: 'pickUpVerifyCode', label: '核销码' },
      createTimeField,
    ],
    actions: [
      {
        key: 'pick-up',
        label: '订单核销',
        type: 'primary',
        permission: 'trade:order:pick-up',
        confirm: '确定要核销该订单吗？',
        handler: row => pickUpTradeOrder(Number(row.id)),
        successText: '核销成功',
      },
    ],
    pageActions: [
      {
        key: 'pick-up-code',
        label: '核销码核销',
        type: 'success',
        permission: 'trade:order:pick-up',
        fields: [
          { prop: 'pickUpVerifyCode', label: '核销码', type: 'text', required: true },
        ],
        confirm: '确定要核销该核销码对应的订单吗？',
        handler: (_, data) => pickUpTradeOrderByVerifyCode(String(data?.pickUpVerifyCode || '')),
        successText: '核销成功',
      },
    ],
  },
  brokerageUser: {
    key: 'brokerageUser',
    module: 'trade',
    title: '分销用户',
    emptyText: '暂无分销用户数据',
    permissions: {
      query: 'trade:brokerage-user:query',
      create: 'trade:brokerage-user:create',
      update: 'trade:brokerage-user:update',
    },
    page: pageOf(getTradeBrokerageUserPage),
    detail: id => getTradeBrokerageUser(id) as Promise<Record<string, any>>,
    create: data => createTradeBrokerageUser(data as any),
    listTitle: row => row.nickname || `用户 ${row.id || '-'}`,
    listSubtitle: row => `推广员：${row.bindUserId ?? '-'}`,
    listImage: row => row.avatar,
    statusField: { prop: 'brokerageEnabled', label: '推广资格', type: 'boolean' },
    searchFields: [
      { prop: 'nickname', label: '用户昵称', type: 'text' },
      { prop: 'brokerageEnabled', label: '推广资格', type: 'boolean', defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'price', label: '可用佣金', type: 'money' },
      { prop: 'frozenPrice', label: '冻结佣金', type: 'money' },
      { prop: 'brokerageTime', label: '成为分销员时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'id', label: '用户编号', type: 'number' },
      { prop: 'nickname', label: '用户昵称' },
      { prop: 'avatar', label: '头像', type: 'image' },
      { prop: 'bindUserId', label: '推广员编号', type: 'number' },
      { prop: 'bindUserTime', label: '绑定时间', type: 'datetime' },
      { prop: 'brokerageEnabled', label: '推广资格', type: 'boolean' },
      { prop: 'price', label: '可用佣金', type: 'money' },
      { prop: 'frozenPrice', label: '冻结佣金', type: 'money' },
    ],
    formFields: [
      { prop: 'id', label: '用户编号', type: 'number', required: true },
      { prop: 'bindUserId', label: '推广员编号', type: 'number' },
    ],
    defaultForm: () => ({ id: undefined, bindUserId: undefined }),
    actions: [
      {
        key: 'update-bind-user',
        label: '修改推广员',
        type: 'primary',
        permission: 'trade:brokerage-user:update-bind-user',
        fields: [{ prop: 'bindUserId', label: '推广员编号', type: 'number', required: true }],
        defaultForm: row => ({ id: row.id, bindUserId: row.bindUserId }),
        handler: (row, data) => updateTradeBrokerageUser({ id: row.id, ...data }),
        successText: '修改成功',
      },
      {
        key: 'clear-bind-user',
        label: '清除推广员',
        type: 'warning',
        permission: 'trade:brokerage-user:clear-bind-user',
        confirm: '确定要清除该用户的推广员吗？',
        handler: row => clearTradeBrokerageUserBind(Number(row.id)),
        successText: '清除成功',
      },
      {
        key: 'update-enabled',
        label: '修改推广资格',
        type: 'warning',
        permission: 'trade:brokerage-user:update-brokerage-enabled',
        fields: [{ prop: 'brokerageEnabled', label: '推广资格', type: 'boolean', required: true }],
        defaultForm: row => ({ id: row.id, brokerageEnabled: !row.brokerageEnabled }),
        handler: (row, data) => updateTradeBrokerageUserEnabled({ id: Number(row.id), brokerageEnabled: !!data?.brokerageEnabled }),
        successText: '修改成功',
      },
    ],
  },
  brokerageRecord: {
    key: 'brokerageRecord',
    module: 'trade',
    title: '佣金记录',
    emptyText: '暂无佣金记录',
    permissions: { query: 'trade:brokerage-record:query' },
    page: pageOf(getTradeBrokerageRecordPage),
    detail: id => getTradeBrokerageRecord(id) as Promise<Record<string, any>>,
    listTitle: row => row.title || `记录 ${row.id || '-'}`,
    listSubtitle: row => `用户编号：${row.userId ?? '-'}`,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.BROKERAGE_RECORD_STATUS },
    searchFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'bizType', label: '业务类型', type: 'dict', dictType: DICT_TYPE.BROKERAGE_RECORD_BIZ_TYPE, defaultValue: -1 },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.BROKERAGE_RECORD_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'price', label: '佣金', type: 'money' },
      { prop: 'totalPrice', label: '当前佣金', type: 'money' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'bizType', label: '业务类型', dictType: DICT_TYPE.BROKERAGE_RECORD_BIZ_TYPE },
      { prop: 'bizId', label: '业务编号', type: 'number' },
      { prop: 'title', label: '标题' },
      { prop: 'price', label: '佣金', type: 'money' },
      { prop: 'totalPrice', label: '当前佣金', type: 'money' },
      { prop: 'status', label: '状态', dictType: DICT_TYPE.BROKERAGE_RECORD_STATUS },
      { prop: 'unfreezeTime', label: '解冻时间', type: 'datetime' },
      createTimeField,
    ],
  },
  brokerageWithdraw: {
    key: 'brokerageWithdraw',
    module: 'trade',
    title: '佣金提现',
    emptyText: '暂无佣金提现',
    permissions: { query: 'trade:brokerage-withdraw:query' },
    page: pageOf(getTradeBrokerageWithdrawPage),
    detail: id => getTradeBrokerageWithdraw(id) as Promise<Record<string, any>>,
    listTitle: row => row.userName || `提现 ${row.id || '-'}`,
    listSubtitle: row => row.userAccount || `用户编号：${row.userId ?? '-'}`,
    statusField: { prop: 'status', label: '提现状态', dictType: DICT_TYPE.BROKERAGE_WITHDRAW_STATUS },
    searchFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'type', label: '提现类型', type: 'dict', dictType: DICT_TYPE.BROKERAGE_WITHDRAW_TYPE, defaultValue: -1 },
      { prop: 'status', label: '提现状态', type: 'dict', dictType: DICT_TYPE.BROKERAGE_WITHDRAW_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'price', label: '提现金额', type: 'money' },
      { prop: 'feePrice', label: '手续费', type: 'money' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'price', label: '提现金额', type: 'money' },
      { prop: 'feePrice', label: '手续费', type: 'money' },
      { prop: 'totalPrice', label: '到账金额', type: 'money' },
      { prop: 'type', label: '提现类型', dictType: DICT_TYPE.BROKERAGE_WITHDRAW_TYPE },
      { prop: 'userName', label: '姓名' },
      { prop: 'userAccount', label: '账号' },
      { prop: 'bankName', label: '银行', dictType: DICT_TYPE.BROKERAGE_BANK_NAME },
      { prop: 'status', label: '提现状态', dictType: DICT_TYPE.BROKERAGE_WITHDRAW_STATUS },
      { prop: 'auditReason', label: '审核备注', type: 'textarea' },
      { prop: 'transferErrorMsg', label: '转账错误', type: 'textarea' },
      createTimeField,
    ],
    actions: [
      {
        key: 'approve',
        label: '通过申请',
        type: 'primary',
        permission: 'trade:brokerage-withdraw:audit',
        confirm: '确定通过该提现申请吗？',
        handler: row => approveTradeBrokerageWithdraw(Number(row.id)),
        successText: '审核通过',
      },
      {
        key: 'reject',
        label: '驳回申请',
        type: 'danger',
        permission: 'trade:brokerage-withdraw:audit',
        fields: [{ prop: 'auditReason', label: '驳回原因', type: 'textarea', required: true }],
        defaultForm: row => ({ id: row.id, auditReason: '' }),
        handler: (row, data) => rejectTradeBrokerageWithdraw({ ...row, ...data }),
        successText: '驳回成功',
      },
    ],
  },
  promotionCouponTemplate: {
    key: 'promotionCouponTemplate',
    module: 'promotion',
    title: '优惠券模板',
    emptyText: '暂无优惠券模板',
    permissions: {
      query: 'promotion:coupon-template:query',
      create: 'promotion:coupon-template:create',
      update: 'promotion:coupon-template:update',
      delete: 'promotion:coupon-template:delete',
    },
    page: pageOf(getPromotionCouponTemplatePage),
    detail: id => getPromotionCouponTemplate(id) as Promise<Record<string, any>>,
    create: data => createPromotionCouponTemplate(data as any),
    update: data => updatePromotionCouponTemplate(data as any),
    delete: deletePromotionCouponTemplate,
    listTitle: row => row.name || '-',
    listSubtitle: row => `领取 ${row.takeCount || 0} / 使用 ${row.useCount || 0}`,
    statusField: commonStatusField,
    searchFields: [
      { prop: 'name', label: '模板名称', type: 'text' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'totalCount', label: '发放数量', type: 'number' },
      { prop: 'takeLimitCount', label: '每人限领', type: 'number' },
      { prop: 'usePrice', label: '使用门槛', type: 'money' },
    ],
    detailFields: [
      { prop: 'name', label: '模板名称' },
      commonStatusField,
      { prop: 'totalCount', label: '发放数量', type: 'number' },
      { prop: 'takeLimitCount', label: '每人限领', type: 'number' },
      { prop: 'takeType', label: '领取方式', dictType: DICT_TYPE.PROMOTION_COUPON_TAKE_TYPE },
      { prop: 'usePrice', label: '使用门槛', type: 'money' },
      { prop: 'discountType', label: '优惠类型', dictType: DICT_TYPE.PROMOTION_DISCOUNT_TYPE },
      { prop: 'discountPrice', label: '优惠金额', type: 'money' },
      { prop: 'discountPercent', label: '折扣百分比', type: 'number' },
      { prop: 'productScopeValues', label: '商品范围值', type: 'array' },
      createTimeField,
    ],
    formFields: [
      { prop: 'name', label: '模板名称', type: 'text', required: true },
      { prop: 'totalCount', label: '发放数量', type: 'number', required: true },
      { prop: 'takeLimitCount', label: '每人限领', type: 'number', required: true },
      { prop: 'takeType', label: '领取方式', type: 'dict', dictType: DICT_TYPE.PROMOTION_COUPON_TAKE_TYPE, required: true },
      { prop: 'usePrice', label: '使用门槛', type: 'money', required: true },
      { prop: 'productScope', label: '商品范围', type: 'number', required: true },
      { prop: 'productScopeValues', label: '商品范围值', type: 'array', arrayValueType: 'number' },
      { prop: 'validityType', label: '有效期类型', type: 'dict', dictType: DICT_TYPE.PROMOTION_COUPON_TEMPLATE_VALIDITY_TYPE, required: true },
      { prop: 'validStartTime', label: '固定开始', type: 'datetime' },
      { prop: 'validEndTime', label: '固定结束', type: 'datetime' },
      { prop: 'fixedStartTerm', label: '领取后第几天生效', type: 'number' },
      { prop: 'fixedEndTerm', label: '有效天数', type: 'number' },
      { prop: 'discountType', label: '优惠类型', type: 'dict', dictType: DICT_TYPE.PROMOTION_DISCOUNT_TYPE, required: true },
      { prop: 'discountPrice', label: '优惠金额', type: 'money' },
      { prop: 'discountPercent', label: '折扣百分比', type: 'number' },
      { prop: 'discountLimitPrice', label: '最多优惠', type: 'money' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
    ],
    defaultForm: () => ({
      id: undefined,
      name: '',
      totalCount: 0,
      takeLimitCount: 1,
      takeType: 1,
      usePrice: 0,
      productScope: 1,
      productScopeValues: '',
      validityType: 1,
      validStartTime: '',
      validEndTime: '',
      fixedStartTerm: 0,
      fixedEndTerm: 7,
      discountType: 1,
      discountPrice: 0,
      discountPercent: 0,
      discountLimitPrice: 0,
      status: CommonStatusEnum.ENABLE,
    }),
    actions: [
      {
        key: 'enable',
        label: '启用模板',
        type: 'primary',
        permission: 'promotion:coupon-template:update',
        visible: row => row.status !== CommonStatusEnum.ENABLE,
        confirm: '确定启用该优惠券模板吗？',
        handler: row => updatePromotionCouponTemplateStatus({ id: Number(row.id), status: CommonStatusEnum.ENABLE }),
        successText: '启用成功',
      },
      {
        key: 'disable',
        label: '禁用模板',
        type: 'warning',
        permission: 'promotion:coupon-template:update',
        visible: row => row.status === CommonStatusEnum.ENABLE,
        confirm: '确定禁用该优惠券模板吗？',
        handler: row => updatePromotionCouponTemplateStatus({ id: Number(row.id), status: CommonStatusEnum.DISABLE }),
        successText: '禁用成功',
      },
    ],
  },
  promotionCoupon: {
    key: 'promotionCoupon',
    module: 'promotion',
    title: '优惠券',
    emptyText: '暂无优惠券',
    permissions: { query: 'promotion:coupon:query', delete: 'promotion:coupon:delete' },
    page: pageOf(getPromotionCouponPage),
    detail: localDetail(pageOf(getPromotionCouponPage)),
    delete: deletePromotionCoupon,
    listTitle: row => row.name || `优惠券 ${row.id || '-'}`,
    listSubtitle: row => `用户编号：${row.userId ?? '-'}`,
    statusField: { prop: 'status', label: '状态', dictType: DICT_TYPE.PROMOTION_COUPON_STATUS },
    searchFields: [
      { prop: 'templateId', label: '模板编号', type: 'number' },
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.PROMOTION_COUPON_STATUS, defaultValue: -1 },
    ],
    cardFields: [
      { prop: 'usePrice', label: '使用门槛', type: 'money' },
      { prop: 'discountPrice', label: '优惠金额', type: 'money' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'templateId', label: '模板编号', type: 'number' },
      { prop: 'name', label: '优惠券名称' },
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'discountType', label: '优惠类型', dictType: DICT_TYPE.PROMOTION_DISCOUNT_TYPE },
      { prop: 'status', label: '状态', dictType: DICT_TYPE.PROMOTION_COUPON_STATUS },
      { prop: 'useTime', label: '使用时间', type: 'datetime' },
      createTimeField,
    ],
    actions: [
      {
        key: 'send',
        label: '发送优惠券',
        type: 'primary',
        permission: 'promotion:coupon:send',
        fields: [
          { prop: 'templateId', label: '模板编号', type: 'number', required: true },
          { prop: 'userIds', label: '用户编号', type: 'array', arrayValueType: 'number', required: true },
        ],
        defaultForm: row => ({ templateId: row.templateId, userIds: row.userId ? String(row.userId) : '' }),
        handler: (_row, data) => sendPromotionCoupon(data as any),
        successText: '发送成功',
      },
    ],
  },
  promotionDiscountActivity: {
    key: 'promotionDiscountActivity',
    module: 'promotion',
    title: '限时折扣',
    emptyText: '暂无限时折扣活动',
    permissions: { query: 'promotion:discount-activity:query', create: 'promotion:discount-activity:create', update: 'promotion:discount-activity:update', delete: 'promotion:discount-activity:delete' },
    page: pageOf(getPromotionDiscountActivityPage),
    detail: id => getPromotionDiscountActivity(id) as Promise<Record<string, any>>,
    create: data => createPromotionDiscountActivity(data as any),
    update: data => updatePromotionDiscountActivity(data as any),
    delete: deletePromotionDiscountActivity,
    formUrl: activityFormUrl('promotionDiscountActivity'),
    listTitle: row => row.name || '-',
    listSubtitle: row => row.remark || `商品编号：${row.spuId ?? '-'}`,
    statusField: activityStatusField,
    searchFields: [{ prop: 'name', label: '活动名称', type: 'text' }],
    cardFields: activityCardFields,
    detailFields: activityDetailFields,
    formFields: activityFormFields,
    defaultForm: activityDefault,
    actions: [closeAction(closePromotionDiscountActivity, 'promotion:discount-activity:close')],
  },
  promotionRewardActivity: {
    key: 'promotionRewardActivity',
    module: 'promotion',
    title: '满减送',
    emptyText: '暂无满减送活动',
    permissions: { query: 'promotion:reward-activity:query', create: 'promotion:reward-activity:create', update: 'promotion:reward-activity:update', delete: 'promotion:reward-activity:delete' },
    page: pageOf(getPromotionRewardActivityPage),
    detail: id => getPromotionRewardActivity(id) as Promise<Record<string, any>>,
    create: data => createPromotionRewardActivity(data as any),
    update: data => updatePromotionRewardActivity(data as any),
    delete: deletePromotionRewardActivity,
    formUrl: activityFormUrl('promotionRewardActivity'),
    listTitle: row => row.name || '-',
    listSubtitle: row => row.remark || '暂无备注',
    statusField: activityStatusField,
    searchFields: [{ prop: 'name', label: '活动名称', type: 'text' }],
    cardFields: activityCardFields,
    detailFields: [
      { prop: 'name', label: '活动名称' },
      activityStatusField,
      { prop: 'conditionType', label: '条件类型', type: 'number' },
      { prop: 'productScope', label: '商品范围', type: 'number' },
      { prop: 'productScopeValues', label: '商品范围值', type: 'array' },
      { prop: 'rules', label: '优惠规则', type: 'json' },
      createTimeField,
    ],
    formFields: [
      { prop: 'name', label: '活动名称', type: 'text', required: true },
      { prop: 'startTime', label: '开始时间', type: 'datetime', required: true },
      { prop: 'endTime', label: '结束时间', type: 'datetime', required: true },
      { prop: 'conditionType', label: '条件类型', type: 'number', required: true },
      { prop: 'productScope', label: '商品范围', type: 'number', required: true },
      { prop: 'productScopeValues', label: '商品范围值', type: 'array', arrayValueType: 'number' },
      { prop: 'rules', label: '优惠规则 JSON', type: 'json', required: true },
      { prop: 'remark', label: '备注', type: 'textarea' },
    ],
    defaultForm: () => ({ id: undefined, name: '', startTime: '', endTime: '', conditionType: 1, productScope: 1, productScopeValues: '', rules: '[]', remark: '' }),
    actions: [closeAction(closePromotionRewardActivity, 'promotion:reward-activity:close')],
  },
  promotionSeckillActivity: {
    key: 'promotionSeckillActivity',
    module: 'promotion',
    title: '秒杀活动',
    emptyText: '暂无秒杀活动',
    permissions: { query: 'promotion:seckill-activity:query', create: 'promotion:seckill-activity:create', update: 'promotion:seckill-activity:update', delete: 'promotion:seckill-activity:delete' },
    page: pageOf(getPromotionSeckillActivityPage),
    detail: id => getPromotionSeckillActivity(id) as Promise<Record<string, any>>,
    create: data => createPromotionSeckillActivity(data as any),
    update: data => updatePromotionSeckillActivity(data as any),
    delete: deletePromotionSeckillActivity,
    formUrl: activityFormUrl('promotionSeckillActivity'),
    listTitle: row => row.name || '-',
    listSubtitle: row => `商品编号：${row.spuId ?? '-'}`,
    statusField: activityStatusField,
    searchFields: [{ prop: 'name', label: '活动名称', type: 'text' }],
    cardFields: [...activityCardFields, { prop: 'seckillPrice', label: '秒杀价', type: 'money' }],
    detailFields: [...activityDetailFields, { prop: 'configIds', label: '秒杀时段' }, { prop: 'seckillPrice', label: '秒杀价', type: 'money' }],
    formFields: [...activityFormFields, { prop: 'configIds', label: '秒杀时段编号', type: 'text' }, { prop: 'sort', label: '排序', type: 'number' }],
    defaultForm: () => ({ ...activityDefault(), configIds: '', sort: 0 }),
    actions: [closeAction(closePromotionSeckillActivity, 'promotion:seckill-activity:close')],
  },
  promotionSeckillConfig: {
    key: 'promotionSeckillConfig',
    module: 'promotion',
    title: '秒杀时段',
    emptyText: '暂无秒杀时段',
    permissions: { query: 'promotion:seckill-config:query', create: 'promotion:seckill-config:create', update: 'promotion:seckill-config:update', delete: 'promotion:seckill-config:delete' },
    page: pageOf(getPromotionSeckillConfigPage),
    detail: id => getPromotionSeckillConfig(id) as Promise<Record<string, any>>,
    create: data => createPromotionSeckillConfig(data as any),
    update: data => updatePromotionSeckillConfig(data as any),
    delete: deletePromotionSeckillConfig,
    listTitle: row => row.name || '-',
    listSubtitle: row => `${row.startTime || '-'} - ${row.endTime || '-'}`,
    statusField: commonStatusField,
    searchFields: [{ prop: 'name', label: '时段名称', type: 'text' }],
    cardFields: [
      { prop: 'startTime', label: '开始时间' },
      { prop: 'endTime', label: '结束时间' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'name', label: '时段名称' },
      { prop: 'startTime', label: '开始时间' },
      { prop: 'endTime', label: '结束时间' },
      { prop: 'sliderPicUrls', label: '轮播图', type: 'array' },
      commonStatusField,
      createTimeField,
    ],
    formFields: [
      { prop: 'name', label: '时段名称', type: 'text', required: true },
      { prop: 'startTime', label: '开始时间', type: 'text', required: true },
      { prop: 'endTime', label: '结束时间', type: 'text', required: true },
      { prop: 'sliderPicUrls', label: '轮播图 URL', type: 'array', required: true },
      { prop: 'status', label: '状态', type: 'dict', dictType: DICT_TYPE.COMMON_STATUS, required: true },
    ],
    defaultForm: () => ({ id: undefined, name: '', startTime: '00:00', endTime: '01:00', sliderPicUrls: '', status: CommonStatusEnum.ENABLE }),
    actions: [
      {
        key: 'toggle-status',
        label: '切换状态',
        type: 'warning',
        permission: 'promotion:seckill-config:update',
        confirm: '确定要切换该秒杀时段状态吗？',
        handler: row => updatePromotionSeckillConfigStatus({
          id: Number(row.id),
          status: row.status === CommonStatusEnum.ENABLE ? CommonStatusEnum.DISABLE : CommonStatusEnum.ENABLE,
        }),
        successText: '切换成功',
      },
    ],
  },
  promotionCombinationActivity: {
    key: 'promotionCombinationActivity',
    module: 'promotion',
    title: '拼团活动',
    emptyText: '暂无拼团活动',
    permissions: { query: 'promotion:combination-activity:query', create: 'promotion:combination-activity:create', update: 'promotion:combination-activity:update', delete: 'promotion:combination-activity:delete' },
    page: pageOf(getPromotionCombinationActivityPage),
    detail: id => getPromotionCombinationActivity(id) as Promise<Record<string, any>>,
    create: data => createPromotionCombinationActivity(data as any),
    update: data => updatePromotionCombinationActivity(data as any),
    delete: deletePromotionCombinationActivity,
    formUrl: activityFormUrl('promotionCombinationActivity'),
    listTitle: row => row.name || '-',
    listSubtitle: row => `成团人数：${row.userSize ?? '-'}`,
    statusField: activityStatusField,
    searchFields: [{ prop: 'name', label: '活动名称', type: 'text' }],
    cardFields: [...activityCardFields, { prop: 'combinationPrice', label: '拼团价', type: 'money' }],
    detailFields: [...activityDetailFields, { prop: 'userSize', label: '成团人数', type: 'number' }, { prop: 'limitDuration', label: '限制时长', type: 'number' }],
    formFields: [...activityFormFields, { prop: 'userSize', label: '成团人数', type: 'number', required: true }, { prop: 'limitDuration', label: '限制时长', type: 'number' }],
    defaultForm: () => ({ ...activityDefault(), userSize: 2, limitDuration: 24 }),
    actions: [closeAction(closePromotionCombinationActivity, 'promotion:combination-activity:close')],
  },
  promotionCombinationRecord: {
    key: 'promotionCombinationRecord',
    module: 'promotion',
    title: '拼团记录',
    emptyText: '暂无拼团记录',
    permissions: { query: 'promotion:combination-record:query' },
    page: pageOf(getPromotionCombinationRecordPage),
    detail: localDetail(pageOf(getPromotionCombinationRecordPage)),
    listTitle: row => row.spuName || `拼团 ${row.id || '-'}`,
    listSubtitle: row => row.nickname || '暂无用户信息',
    listImage: row => row.picUrl || row.avatar,
    statusField: activityStatusField,
    searchFields: [
      { prop: 'activityId', label: '活动编号', type: 'number' },
      { prop: 'status', label: '状态', type: 'number' },
    ],
    cardFields: [
      { prop: 'userSize', label: '成团人数', type: 'number' },
      { prop: 'userCount', label: '已参团人数', type: 'number' },
      { prop: 'startTime', label: '开始时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'activityId', label: '活动编号', type: 'number' },
      { prop: 'spuName', label: '商品名称' },
      { prop: 'nickname', label: '用户昵称' },
      activityStatusField,
      { prop: 'virtualGroup', label: '虚拟成团', type: 'boolean' },
      { prop: 'expireTime', label: '过期时间', type: 'datetime' },
    ],
  },
  promotionBargainActivity: {
    key: 'promotionBargainActivity',
    module: 'promotion',
    title: '砍价活动',
    emptyText: '暂无砍价活动',
    permissions: { query: 'promotion:bargain-activity:query', create: 'promotion:bargain-activity:create', update: 'promotion:bargain-activity:update', delete: 'promotion:bargain-activity:delete' },
    page: pageOf(getPromotionBargainActivityPage),
    detail: id => getPromotionBargainActivity(id) as Promise<Record<string, any>>,
    create: data => createPromotionBargainActivity(data as any),
    update: data => updatePromotionBargainActivity(data as any),
    delete: deletePromotionBargainActivity,
    formUrl: activityFormUrl('promotionBargainActivity'),
    listTitle: row => row.name || '-',
    listSubtitle: row => `商品编号：${row.spuId ?? '-'}`,
    statusField: activityStatusField,
    searchFields: [{ prop: 'name', label: '活动名称', type: 'text' }],
    cardFields: [
      { prop: 'bargainFirstPrice', label: '起始价', type: 'money' },
      { prop: 'bargainMinPrice', label: '底价', type: 'money' },
      { prop: 'stock', label: '库存', type: 'number' },
    ],
    detailFields: [
      { prop: 'name', label: '活动名称' },
      activityStatusField,
      { prop: 'spuId', label: '商品编号', type: 'number' },
      { prop: 'skuId', label: 'SKU 编号', type: 'number' },
      { prop: 'bargainFirstPrice', label: '起始价', type: 'money' },
      { prop: 'bargainMinPrice', label: '底价', type: 'money' },
      { prop: 'stock', label: '库存', type: 'number' },
      { prop: 'startTime', label: '开始时间', type: 'datetime' },
      { prop: 'endTime', label: '结束时间', type: 'datetime' },
    ],
    formFields: [
      { prop: 'name', label: '活动名称', type: 'text', required: true },
      { prop: 'spuId', label: '商品编号', type: 'number', required: true },
      { prop: 'skuId', label: 'SKU 编号', type: 'number', required: true },
      { prop: 'startTime', label: '开始时间', type: 'datetime', required: true },
      { prop: 'endTime', label: '结束时间', type: 'datetime', required: true },
      { prop: 'bargainFirstPrice', label: '起始价', type: 'money', required: true },
      { prop: 'bargainMinPrice', label: '底价', type: 'money', required: true },
      { prop: 'stock', label: '库存', type: 'number', required: true },
      { prop: 'helpMaxCount', label: '助力人数', type: 'number' },
      { prop: 'bargainCount', label: '帮砍次数', type: 'number' },
      { prop: 'totalLimitCount', label: '限购数量', type: 'number' },
    ],
    defaultForm: () => ({ id: undefined, name: '', spuId: undefined, skuId: undefined, startTime: '', endTime: '', bargainFirstPrice: 0, bargainMinPrice: 0, stock: 0, helpMaxCount: 1, bargainCount: 1, totalLimitCount: 1 }),
    actions: [closeAction(closePromotionBargainActivity, 'promotion:bargain-activity:close')],
  },
  promotionBargainRecord: {
    key: 'promotionBargainRecord',
    module: 'promotion',
    title: '砍价记录',
    emptyText: '暂无砍价记录',
    permissions: { query: 'promotion:bargain-record:query' },
    page: pageOf(getPromotionBargainRecordPage),
    detail: localDetail(pageOf(getPromotionBargainRecordPage)),
    listTitle: row => `砍价记录 ${row.id || '-'}`,
    listSubtitle: row => `用户编号：${row.userId ?? '-'}`,
    statusField: activityStatusField,
    searchFields: [
      { prop: 'activityId', label: '活动编号', type: 'number' },
      { prop: 'userId', label: '用户编号', type: 'number' },
    ],
    cardFields: [
      { prop: 'bargainFirstPrice', label: '起始价', type: 'money' },
      { prop: 'bargainPrice', label: '已砍金额', type: 'money' },
      { prop: 'endTime', label: '结束时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'activityId', label: '活动编号', type: 'number' },
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'spuId', label: '商品编号', type: 'number' },
      activityStatusField,
      { prop: 'orderId', label: '订单编号', type: 'number' },
      { prop: 'endTime', label: '结束时间', type: 'datetime' },
    ],
  },
  promotionBargainHelp: {
    key: 'promotionBargainHelp',
    module: 'promotion',
    title: '砍价助力',
    emptyText: '暂无砍价助力',
    permissions: { query: 'promotion:bargain-help:query' },
    page: pageOf(getPromotionBargainHelpPage),
    detail: localDetail(pageOf(getPromotionBargainHelpPage)),
    listTitle: row => `助力记录 ${row.id || '-'}`,
    listSubtitle: row => `用户编号：${row.userId ?? '-'}`,
    searchFields: [
      { prop: 'record', label: '砍价记录', type: 'number' },
      { prop: 'userId', label: '用户编号', type: 'number' },
    ],
    cardFields: [
      { prop: 'reducePrice', label: '助力金额', type: 'money' },
      { prop: 'endTime', label: '结束时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'record', label: '砍价记录', type: 'number' },
      { prop: 'userId', label: '用户编号', type: 'number' },
      { prop: 'reducePrice', label: '助力金额', type: 'money' },
      { prop: 'endTime', label: '结束时间', type: 'datetime' },
    ],
  },
  promotionPointActivity: {
    key: 'promotionPointActivity',
    module: 'promotion',
    title: '积分商城',
    emptyText: '暂无积分商城活动',
    permissions: { query: 'promotion:point-activity:query', create: 'promotion:point-activity:create', update: 'promotion:point-activity:update', delete: 'promotion:point-activity:delete' },
    page: pageOf(getPromotionPointActivityPage),
    detail: id => getPromotionPointActivity(id) as Promise<Record<string, any>>,
    create: data => createPromotionPointActivity(data as any),
    update: data => updatePromotionPointActivity(data as any),
    delete: deletePromotionPointActivity,
    formUrl: activityFormUrl('promotionPointActivity'),
    listTitle: row => row.spuName || `商品 ${row.spuId || '-'}`,
    listSubtitle: row => row.remark || '暂无备注',
    listImage: row => row.picUrl,
    statusField: activityStatusField,
    searchFields: [
      { prop: 'spuId', label: '商品编号', type: 'number' },
      { prop: 'status', label: '状态', type: 'number' },
    ],
    cardFields: [
      { prop: 'point', label: '兑换积分', type: 'number' },
      { prop: 'price', label: '兑换金额', type: 'money' },
      { prop: 'stock', label: '库存', type: 'number' },
    ],
    detailFields: [
      { prop: 'spuId', label: '商品编号', type: 'number' },
      { prop: 'spuName', label: '商品名称' },
      { prop: 'picUrl', label: '商品图片', type: 'image' },
      activityStatusField,
      { prop: 'point', label: '兑换积分', type: 'number' },
      { prop: 'price', label: '兑换金额', type: 'money' },
      { prop: 'stock', label: '库存', type: 'number' },
      { prop: 'products', label: '商品规则', type: 'json' },
      createTimeField,
    ],
    formFields: [
      { prop: 'spuId', label: '商品编号', type: 'number', required: true },
      { prop: 'sort', label: '排序', type: 'number', required: true },
      { prop: 'products', label: '商品规则 JSON', type: 'json', required: true },
      { prop: 'remark', label: '备注', type: 'textarea' },
    ],
    defaultForm: () => ({ id: undefined, spuId: undefined, sort: 0, products: '[]', remark: '' }),
    actions: [closeAction(closePromotionPointActivity, 'promotion:point-activity:close')],
  },
  promotionDiyPage: {
    key: 'promotionDiyPage',
    module: 'promotion',
    title: '装修页面',
    emptyText: '暂无装修页面',
    permissions: { query: 'promotion:diy-page:query', create: 'promotion:diy-page:create', update: 'promotion:diy-page:update', delete: 'promotion:diy-page:delete' },
    page: pageOf(getPromotionDiyPagePage),
    detail: id => getPromotionDiyPage(id) as Promise<Record<string, any>>,
    create: data => createPromotionDiyPage(data as any),
    update: data => updatePromotionDiyPage(data as any),
    delete: deletePromotionDiyPage,
    formUrl: diyFormUrl('promotionDiyPage'),
    listTitle: row => row.name || '-',
    listSubtitle: row => row.remark || `模板编号：${row.templateId ?? '-'}`,
    listImage: row => row.previewPicUrls?.[0],
    searchFields: [{ prop: 'name', label: '页面名称', type: 'text' }],
    cardFields: [
      { prop: 'templateId', label: '模板编号', type: 'number' },
      createTimeField,
    ],
    detailFields: [
      { prop: 'name', label: '页面名称' },
      { prop: 'templateId', label: '模板编号', type: 'number' },
      { prop: 'previewPicUrls', label: '预览图', type: 'array' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      { prop: 'property', label: '装修属性', type: 'json' },
      createTimeField,
    ],
    formFields: [
      { prop: 'templateId', label: '模板编号', type: 'number' },
      { prop: 'name', label: '页面名称', type: 'text', required: true },
      { prop: 'previewPicUrls', label: '预览图 URL', type: 'array' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      { prop: 'property', label: '装修属性 JSON', type: 'json', required: true },
    ],
    defaultForm: () => ({ id: undefined, templateId: undefined, name: '', previewPicUrls: '', remark: '', property: '{}' }),
  },
  promotionDiyTemplate: {
    key: 'promotionDiyTemplate',
    module: 'promotion',
    title: '装修模板',
    emptyText: '暂无装修模板',
    permissions: { query: 'promotion:diy-template:query', create: 'promotion:diy-template:create', update: 'promotion:diy-template:update', delete: 'promotion:diy-template:delete' },
    page: pageOf(getPromotionDiyTemplatePage),
    detail: id => getPromotionDiyTemplate(id) as Promise<Record<string, any>>,
    create: data => createPromotionDiyTemplate(data as any),
    update: data => updatePromotionDiyTemplate(data as any),
    delete: deletePromotionDiyTemplate,
    formUrl: diyFormUrl('promotionDiyTemplate'),
    listTitle: row => row.name || '-',
    listSubtitle: row => row.used ? '当前使用中' : row.remark || '未使用',
    listImage: row => row.previewPicUrls?.[0],
    statusField: { prop: 'used', label: '是否使用', type: 'boolean' },
    searchFields: [{ prop: 'name', label: '模板名称', type: 'text' }],
    cardFields: [
      { prop: 'used', label: '是否使用', type: 'boolean' },
      { prop: 'usedTime', label: '使用时间', type: 'datetime' },
    ],
    detailFields: [
      { prop: 'name', label: '模板名称' },
      { prop: 'used', label: '是否使用', type: 'boolean' },
      { prop: 'usedTime', label: '使用时间', type: 'datetime' },
      { prop: 'previewPicUrls', label: '预览图', type: 'array' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      { prop: 'property', label: '装修属性', type: 'json' },
      createTimeField,
    ],
    formFields: [
      { prop: 'name', label: '模板名称', type: 'text', required: true },
      { prop: 'previewPicUrls', label: '预览图 URL', type: 'array' },
      { prop: 'remark', label: '备注', type: 'textarea' },
      { prop: 'property', label: '装修属性 JSON', type: 'json', required: true },
    ],
    defaultForm: () => ({ id: undefined, name: '', previewPicUrls: '', remark: '', property: '{}' }),
    actions: [
      {
        key: 'use-template',
        label: '使用模板',
        type: 'primary',
        permission: 'promotion:diy-template:update',
        visible: row => !row.used,
        confirm: '确定要使用该装修模板吗？',
        handler: row => usePromotionDiyTemplate(Number(row.id)),
        successText: '使用成功',
      },
    ],
  },
}
